#!/usr/bin/env python3
import argparse,csv,hashlib,json,math,pathlib,re,subprocess,sys
sys.path.insert(0,str(pathlib.Path(__file__).resolve().parents[1]/"channelize_poly"));import run_operator as common
def args():
 p=argparse.ArgumentParser();p.add_argument("--binary",required=True);p.add_argument("--config",required=True);p.add_argument("--thresholds",required=True);p.add_argument("--results-root",required=True);p.add_argument("--scale",required=True);p.add_argument("--run-type",choices=("smoke","formal"),required=True);p.add_argument("--git-commit",required=True);p.add_argument("--git-dirty",required=True);p.add_argument("--test-time-utc",required=True);p.add_argument("--random",required=True);return p.parse_args()
def load(p):raw=pathlib.Path(p).read_bytes();return json.loads(raw.decode()),hashlib.sha256(raw).hexdigest()
def ident(a,c,sha,s,run,case,dev,status,code):return dict(zip(common.IDENTITY,["1",run,a.run_type,a.test_time_utc,a.git_commit,a.git_dirty,c["scale_set_id"],sha,"operator","upfirdn","NA","NA","upfirdn",case,s["scale_id"],s["order_of_magnitude"],str(s["actual_elements"]),";".join(x["input_name"]+"=["+"x".join(map(str,x["shape"]))+"]" for x in s["inputs"]),s["inputs"][0]["dtype"],dev,"not_applicable","compatibility/end-to-end",status,code]))
def main():
 a=args();c,sha=load(a.config);ts,_=load(a.thresholds);ss=[s for o in c["operators"] if o["operator_name"]=="upfirdn" for s in o["scales"] if s["scale_id"]==a.scale]
 if len(ss)!=1:raise ValueError("scale")
 s=ss[0];i=s["inputs"];p=s["parameters"];dtype=i[0]["dtype"]
 if len(i)!=2 or [x["input_name"] for x in i]!=["h","x"] or i[1]["dtype"]!=dtype or s["actual_elements"]!=sum(x["element_count"] for x in i) or p["shape"]!=i[1]["shape"]:raise ValueError("typed inputs")
 out="FP64" if dtype=="INT32" else "FP32";th=[x for x in ts["entries"] if x["dtype"]==dtype][0];warm,measured=(20,100) if a.run_type=="formal" else (1,1);run=f"{a.test_time_utc}_{a.git_commit[:12]}_remaining_operator_case_b04_{a.run_type}_{a.random}";d=pathlib.Path(a.results_root)/a.run_type/run
 if d.exists():raise RuntimeError("exists")
 d.mkdir(parents=True);rawp=d/"upfirdn_probe_raw.json";log=d/"operator_upfirdn_full.log";shape=i[1]["shape"];cmd=[a.binary,"--dtype",dtype,"--rank",str(len(shape)),"--rows",str(shape[0]),"--cols",str(shape[1] if len(shape)==2 else 1),"--taps",str(i[0]["element_count"]),"--axis",str(p["axis"]),"--up",str(p["up"]),"--down",str(p["down"]),"--seed",str(p["generator_seed"]),"--warmup",str(warm),"--measured",str(measured),"--output",str(rawp)];r=subprocess.run(cmd,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT);log.write_text("command="+" ".join(cmd)+"\n"+r.stdout)
 if r.returncode or not rawp.exists():raise RuntimeError(f"probe rc={r.returncode}")
 raw=json.loads(rawp.read_text());n=shape[p["axis"]];nout=(((n-1)*p["up"]+i[0]["element_count"]-1)//p["down"])+1;oshape=list(shape);oshape[p["axis"]]=nout
 if (raw["requested_dtype"],raw["output_dtype"],raw["typed_input_count"],raw["output_shape"])!=(dtype,out,2,oshape):raise RuntimeError("raw")
 ok=all(raw[k]<=th[k+"_max"] for k in ("mse","rmse","relative_l2","relative_linf"));vals=[common.resource_summary(raw[t],k) for t,k in (("cpu_trace","heap"),("cpu_trace","rss"),("gpu_trace","heap"),("gpu_trace","rss"),("gpu_trace","gpu"))];passed=ok and all(x is not None for x in vals);status="PASS" if passed else "FAIL";code="OK" if passed else "FAILED";case=f"upfirdn__{s['scale_id']}__{raw['actual_input_digest'][:16]}";cs,gs=common.stats(raw["cpu_samples_ms"]),common.stats(raw["gpu_samples_ms"]);speed=cs["mean_ms"]/gs["mean_ms"]
 def mr(dev,st,h,rss,gpu):
  q=ident(a,c,sha,s,run,case,dev,status,code);q.update({k:f"{v:.17g}" for k,v in st.items()});q.update({"warmup_runs":str(warm),"measured_runs":str(measured),"cpu_gpu_speedup":f"{speed:.17g}" if dev=="GPU" else "NA","accuracy_reference":"cpu_causal_polyphase_reference","mse":f"{raw['mse']:.17g}" if dev=="GPU" else "0","rmse":f"{raw['rmse']:.17g}" if dev=="GPU" else "0","relative_l2":f"{raw['relative_l2']:.17g}" if dev=="GPU" else "0","relative_linf":f"{raw['relative_linf']:.17g}" if dev=="GPU" else "0","exact_match":"NA","mismatch_count":"NA","semantic_check":th["semantic_rule"]+f":ratio={p['up']}/{p['down']};axis={p['axis']};taps={i[0]['element_count']}","accuracy_status":"PASS" if ok else "FAIL"});
  for pre,val in (("cpu_heap",h),("rss",rss),("gpu",gpu)):
   for f in ("before","after","peak","delta"):q[f"{pre}_{f}_bytes"]=str(val[f]) if val else "NA"
  for k in common.SUMMARY:q.setdefault(k,"NA")
  return q
 common.write_csv(d/f"operator_main_results_upfirdn_not_applicable_{run}.csv",common.IDENTITY+common.SUMMARY,[mr("CPU",cs,vals[0],vals[1],None),mr("GPU",gs,vals[2],vals[3],vals[4])]);tc=common.IDENTITY+["warmup_runs","measured_runs","sample_index","latency_ms","synchronized","input_digest","output_digest"];tr=[]
 for dev,ssamp,od in (("CPU",raw["cpu_samples_ms"],raw["cpu_output_digest"]),("GPU",raw["gpu_samples_ms"],raw["gpu_output_digest"])):
  for n,v in enumerate(ssamp):q=ident(a,c,sha,s,run,case,dev,status,code);q.update({"warmup_runs":str(warm),"measured_runs":str(measured),"sample_index":str(n),"latency_ms":f"{v:.17g}","synchronized":"true","input_digest":raw["actual_input_digest"],"output_digest":od});tr.append(q)
 common.write_csv(d/f"operator_timing_samples_upfirdn_not_applicable_{run}.csv",tc,tr);mc=common.IDENTITY+["sample_index","trace_phase","phase_index","cpu_live_heap_bytes","rss_bytes","gpu_used_bytes"];mem=[]
 for dev,trace in (("CPU",raw["cpu_trace"]),("GPU",raw["gpu_trace"])):
  for x in trace:q=ident(a,c,sha,s,run,case,dev,status,code);q.update({"sample_index":"0","trace_phase":x["phase"],"phase_index":str(x["phase_index"]),"cpu_live_heap_bytes":str(x["heap"]["bytes"]) if x["heap"]["available"] else "NA","rss_bytes":str(x["rss"]["bytes"]) if x["rss"]["available"] else "NA","gpu_used_bytes":str(x["gpu"]["bytes"]) if x["gpu"]["available"] else "NA"});mem.append(q)
 common.write_csv(d/"operator_filtering_upfirdn_memory_trace_not_applicable.csv",mc,mem);common.write_csv(d/f"operator_dtype_evidence_upfirdn_not_applicable_{run}.csv",["run_id","case_id","operator_name","requested_dtype","dtype_semantics","typed_input_count","typed_input_manifest","actual_input_digest","compute_dtype","fft_dtype","output_dtype","status","error_code"],[{"run_id":run,"case_id":case,"operator_name":"upfirdn","requested_dtype":dtype,"dtype_semantics":"actual_same_dtype_h_x_arrays","typed_input_count":"2","typed_input_manifest":raw["typed_input_manifest"],"actual_input_digest":raw["actual_input_digest"],"compute_dtype":"FP32","fft_dtype":"not_applicable","output_dtype":out,"status":status,"error_code":code}]);report={"schema_version":1,"run_id":run,"case_id":case,"operator_name":"upfirdn","scale_id":s["scale_id"],"requested_dtype":dtype,"dtype_semantics":"actual_same_dtype_h_x_arrays","typed_input_names":"h|x","compute_dtype":"FP32","fft_dtype":"not_applicable","output_dtype":out,"backend":"not_applicable","axis":p["axis"],"up":p["up"],"down":p["down"],"tap_count":i[0]["element_count"],"rank":len(shape),"typed_input_count":2,"warmup_runs":warm,"measured_runs":measured,"actual_input_digest":raw["actual_input_digest"],"mse":raw["mse"],"rmse":raw["rmse"],"relative_l2":raw["relative_l2"],"relative_linf":raw["relative_linf"],"status":status,"error_code":code};(d/"operator_upfirdn_report.json").write_text(json.dumps(report,indent=2)+"\n");(d/"operator_upfirdn_summary.txt").write_text("\n".join(f"{k}={v}" for k,v in report.items())+"\n");log.write_text(log.read_text()+json.dumps(report,sort_keys=True)+"\n");print(f"REMAINING_OPERATOR_CASE_UPFIRDN_CASE {status} scale={s['scale_id']} dtype={dtype} backend=not_applicable measured={measured} results={d}");return 0 if passed else 3
if __name__=="__main__":
 try:sys.exit(main())
 except Exception as e:print(f"REMAINING_OPERATOR_CASE_UPFIRDN_DRIVER FAIL error={e}",file=sys.stderr);sys.exit(2)
