#include "accuracy.h"
#include <cusignal/runtime/cuda_utils.h>
#include <cusignal/operators/filtering/filtering_typed.h>
#include "memory.h"
#include "sha256.h"
#include <cuda_fp16.h>
#include <cmath>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>
namespace{namespace fs=std::filesystem;struct C{std::string dtype,mode,bp;int rank{},rows{},cols{},axis{};std::uint64_t seed{};std::size_t warm{},measured{};fs::path out;};struct P{std::string n;int i;zkx::common::ResourceSample h,r,g;};
C cli(int n,char**a){std::map<std::string,std::string>v;for(int i=1;i<n;i+=2)v.emplace(std::string(a[i]).substr(2),a[i+1]);auto g=[&](const char*k)->const std::string&{auto q=v.find(k);if(q==v.end())throw std::invalid_argument(k);return q->second;};return{g("dtype"),g("mode"),g("breakpoints"),std::stoi(g("rank")),std::stoi(g("rows")),std::stoi(g("cols")),std::stoi(g("axis")),std::stoull(g("seed")),std::stoull(g("warmup")),std::stoull(g("measured")),g("output")};}
zkx::common::ResourceSample gs(){return zkx::common::sample_gpu_used([]{auto i=cusignal::cuda_utils::current_memory_info();return(std::int64_t)(i.total_bytes-i.free_bytes);},"cudaMemGetInfo.total_minus_free");}P ph(const char*n,int i,bool g){return{n,i,zkx::common::sample_cpu_heap(),zkx::common::sample_cpu_rss(),g?gs():zkx::common::ResourceSample{false,0,"NA","CPU"}};}template<class T>T cv(float x){return(T)x;}template<>__half cv<__half>(float x){return __float2half_rn(x);}template<class T>std::vector<T>input(std::size_t n,std::uint64_t s){std::vector<T>v;for(std::size_t i=0;i<n;i++){float trend=.05f*i;int noise=static_cast<int>((i*13+s)%9)-4;float z=noise*.25f+trend;v.push_back(cv<T>(std::is_integral_v<T>?float((int)z):z));}return v;}template<class T>std::string dig(const std::vector<T>&v){return zkx::remaining_operator_case::sha256_hex(std::string((char*)v.data(),v.size()*sizeof(T)));}template<class T>double vv(T x){return(double)x;}template<>double vv(__half x){return __half2float(x);}template<class T>std::vector<double>dv(const std::vector<T>&v){std::vector<double>r;for(auto x:v)r.push_back(vv(x));return r;}
std::vector<double>cvv(const cusignal::DetrendCpuResult&r){if(r.dtype==cusignal::DetrendOutputDtype::fp16)return dv(r.fp16);if(r.dtype==cusignal::DetrendOutputDtype::fp32)return dv(r.fp32);return r.fp64;}std::vector<double>gvv(const cusignal::DetrendDeviceResult&r){if(r.dtype==cusignal::DetrendOutputDtype::fp16)return dv(r.fp16.to_host());if(r.dtype==cusignal::DetrendOutputDtype::fp32)return dv(r.fp32.to_host());return r.fp64.to_host();}std::string dn(cusignal::DetrendOutputDtype d){return d==cusignal::DetrendOutputDtype::fp16?"FP16":d==cusignal::DetrendOutputDtype::fp32?"FP32":"FP64";}template<class F>std::vector<double>meas(std::size_t w,std::size_t n,F f){for(std::size_t i=0;i<w;i++)f();std::vector<double>s;for(std::size_t i=0;i<n;i++){auto a=std::chrono::steady_clock::now();f();auto b=std::chrono::steady_clock::now();s.push_back(std::chrono::duration<double,std::milli>(b-a).count());}return s;}void ss(std::ostream&o,const std::vector<double>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<std::setprecision(17)<<v[i];}o<<']';}void rs(std::ostream&o,const zkx::common::ResourceSample&s){o<<"{\"available\":"<<(s.available?"true":"false")<<",\"bytes\":"<<(s.available?std::to_string(s.bytes):"null")<<'}';}void ps(std::ostream&o,const std::vector<P>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<"{\"phase\":\""<<v[i].n<<"\",\"phase_index\":"<<v[i].i<<",\"heap\":";rs(o,v[i].h);o<<",\"rss\":";rs(o,v[i].r);o<<",\"gpu\":";rs(o,v[i].g);o<<'}';}o<<']';}
std::vector<int>bps(std::string s){std::vector<int>v;std::stringstream q(s);std::string x;while(std::getline(q,x,'|'))if(!x.empty())v.push_back(std::stoi(x));return v;}
template<class T>int run(const C&c){auto x=input<T>((size_t)c.rows*(c.rank==2?c.cols:1),c.seed);cusignal::DetrendOptions o;o.shape=c.rank==1?std::vector<int>{c.rows}:std::vector<int>{c.rows,c.cols};o.axis=c.axis;o.mode=c.mode=="constant"?cusignal::DetrendMode::constant:cusignal::DetrendMode::linear;o.breakpoints=bps(c.bp);cusignal::DetrendCpuResult cr;cusignal::DetrendDeviceResult gr;auto ct=meas(c.warm,c.measured,[&]{auto z=x;cr=cusignal::detrend_typed_cpu(z,o);});auto gt=meas(c.warm,c.measured,[&]{auto dx=cusignal::DeviceArray<T>::from_host(x);cusignal::detrend_device(dx,gr,o);gvv(gr);});std::vector<P>cp{ph("before",0,0),ph("allocate",1,0),ph("h2d",2,0)};auto z=x;auto cc=cusignal::detrend_typed_cpu(z,o);cp.push_back(ph("execute_sync",3,0));cp.push_back(ph("d2h",4,0));cc={};cp.push_back(ph("release_sync",5,0));cp.push_back(ph("after",6,0));std::vector<P>gp;gp.push_back(ph("before",0,1));auto dx=cusignal::DeviceArray<T>::from_host(x);cusignal::DetrendDeviceResult gg;gp.push_back(ph("allocate",1,1));gp.push_back(ph("h2d",2,1));cusignal::detrend_device(dx,gg,o);cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("execute_sync",3,1));auto q=gvv(gg);gp.push_back(ph("d2h",4,1));gg={};dx={};cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("release_sync",5,1));gp.push_back(ph("after",6,1));auto a=zkx::common::compare(cvv(cr),gvv(gr),1e-12);if(!std::isfinite(a.mse)||!std::isfinite(a.rmse)||!std::isfinite(a.relative_l2)||!std::isfinite(a.relative_linf))throw std::runtime_error("nonfinite accuracy metric");std::string man="x:"+c.dtype+":["+std::to_string(x.size())+"]:bytes="+std::to_string(x.size()*sizeof(T))+":sha256="+dig(x),id=zkx::remaining_operator_case::sha256_hex(man);if(fs::exists(c.out))throw std::runtime_error("exists");std::ofstream f(c.out);f<<"{\"requested_dtype\":\""<<c.dtype<<"\",\"output_dtype\":\""<<dn(cr.dtype)<<"\",\"mode\":\""<<c.mode<<"\",\"axis\":"<<c.axis<<",\"breakpoints\":\""<<c.bp<<"\",\"typed_input_manifest\":\""<<man<<"\",\"actual_input_digest\":\""<<id<<"\",\"cpu_output_digest\":\""<<dig(cvv(cr))<<"\",\"gpu_output_digest\":\""<<dig(gvv(gr))<<"\",\"mse\":"<<a.mse<<",\"rmse\":"<<a.rmse<<",\"relative_l2\":"<<a.relative_l2<<",\"relative_linf\":"<<a.relative_linf<<",\"cpu_samples_ms\":";ss(f,ct);f<<",\"gpu_samples_ms\":";ss(f,gt);f<<",\"cpu_trace\":";ps(f,cp);f<<",\"gpu_trace\":";ps(f,gp);f<<"}\n";std::cout<<"REMAINING_OPERATOR_CASE_DETREND_PROBE PASS dtype="<<c.dtype<<" mode="<<c.mode<<"\n";return 0;}}
int main(int n,char**a){try{auto c=cli(n,a);if(c.dtype=="FP32")return run<float>(c);if(c.dtype=="FP16")return run<__half>(c);if(c.dtype=="INT32")return run<std::int32_t>(c);if(c.dtype=="INT16")return run<std::int16_t>(c);if(c.dtype=="INT8")return run<std::int8_t>(c);return 2;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}}
