#!/usr/bin/env python3
import argparse,csv,hashlib,json,math,pathlib,re,subprocess,sys
sys.path.insert(0,str(pathlib.Path(__file__).resolve().parents[1]/"channelize_poly"));import run_operator as common
def args():
 p=argparse.ArgumentParser();[p.add_argument("--"+x,required=True) for x in ("binary","config","thresholds","results-root","scale","run-type","git-commit","git-dirty","test-time-utc","random")];return p.parse_args()
def load(p):b=pathlib.Path(p).read_bytes();return json.loads(b.decode()),hashlib.sha256(b).hexdigest()
def ident(a,c,h,s,r,k,d,st,ec):return dict(zip(common.IDENTITY,["1",r,a.run_type,a.test_time_utc,a.git_commit,a.git_dirty,c["scale_set_id"],h,"operator","detrend","NA","NA","detrend",k,s["scale_id"],s["order_of_magnitude"],str(s["actual_elements"]),"x=["+"x".join(map(str,s["inputs"][0]["shape"]))+"]",s["inputs"][0]["dtype"],d,"not_applicable","compatibility/end-to-end",st,ec]))
def main():
 a=args();c,h=load(a.config);t,_=load(a.thresholds);s=[z for o in c["operators"] for z in o["scales"] if z["scale_id"]==a.scale][0];i=s["inputs"][0];p=s["parameters"];dtype=i["dtype"];th=[z for z in t["entries"] if z["dtype"]==dtype][0];w,n=(20,100)if a.run_type=="formal"else(1,1);run=f"{a.test_time_utc}_{a.git_commit[:12]}_remaining_operator_case_b05_{a.run_type}_{a.random}";d=pathlib.Path(a.results_root)/a.run_type/run
 if d.exists():raise RuntimeError("exists")
 d.mkdir(parents=True);rawp=d/"detrend_probe_raw.json";log=d/"operator_detrend_full.log";shape=i["shape"];bp="|".join(map(str,p["breakpoints"]));cmd=[a.binary,"--dtype",dtype,"--mode",p["mode"],"--breakpoints",bp,"--rank",str(len(shape)),"--rows",str(shape[0]),"--cols",str(shape[1]if len(shape)==2 else 1),"--axis",str(p["axis"]),"--seed",str(p["seed"]),"--warmup",str(w),"--measured",str(n),"--output",str(rawp)];q=subprocess.run(cmd,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT);log.write_text("command="+" ".join(cmd)+"\n"+q.stdout)
 if q.returncode:raise RuntimeError("probe")
 raw=json.loads(rawp.read_text());ok=all(raw[x]<=th[x+"_max"]for x in("mse","rmse","relative_l2","relative_linf"));vs=[common.resource_summary(raw[x],y)for x,y in(("cpu_trace","heap"),("cpu_trace","rss"),("gpu_trace","heap"),("gpu_trace","rss"),("gpu_trace","gpu"))];passed=ok and all(x is not None for x in vs);st="PASS"if passed else"FAIL";ec="OK"if passed else"FAILED";case=f"detrend__{s['scale_id']}__{raw['actual_input_digest'][:16]}";cs,gs=common.stats(raw["cpu_samples_ms"]),common.stats(raw["gpu_samples_ms"]);speed=cs["mean_ms"]/gs["mean_ms"]
 def mr(dev,stat,heap,rss,gpu):
  z=ident(a,c,h,s,run,case,dev,st,ec);z.update({k:f"{v:.17g}"for k,v in stat.items()});z.update({"warmup_runs":str(w),"measured_runs":str(n),"cpu_gpu_speedup":f"{speed:.17g}"if dev=="GPU"else"NA","accuracy_reference":"cpu_detrend_reference","mse":str(raw["mse"]if dev=="GPU"else 0),"rmse":str(raw["rmse"]if dev=="GPU"else 0),"relative_l2":str(raw["relative_l2"]if dev=="GPU"else 0),"relative_linf":str(raw["relative_linf"]if dev=="GPU"else 0),"exact_match":"NA","mismatch_count":"NA","semantic_check":th["semantic_rule"],"accuracy_status":"PASS"if ok else"FAIL"});
  for pre,val in(("cpu_heap",heap),("rss",rss),("gpu",gpu)):
   for f in("before","after","peak","delta"):z[f"{pre}_{f}_bytes"]=str(val[f])if val else"NA"
  for k in common.SUMMARY:z.setdefault(k,"NA")
  return z
 common.write_csv(d/f"operator_main_results_detrend_not_applicable_{run}.csv",common.IDENTITY+common.SUMMARY,[mr("CPU",cs,vs[0],vs[1],None),mr("GPU",gs,vs[2],vs[3],vs[4])]);tc=common.IDENTITY+["warmup_runs","measured_runs","sample_index","latency_ms","synchronized","input_digest","output_digest"];tr=[]
 for dev,arr,od in(("CPU",raw["cpu_samples_ms"],raw["cpu_output_digest"]),("GPU",raw["gpu_samples_ms"],raw["gpu_output_digest"])):
  for j,v in enumerate(arr):z=ident(a,c,h,s,run,case,dev,st,ec);z.update({"warmup_runs":str(w),"measured_runs":str(n),"sample_index":str(j),"latency_ms":str(v),"synchronized":"true","input_digest":raw["actual_input_digest"],"output_digest":od});tr.append(z)
 common.write_csv(d/f"operator_timing_samples_detrend_not_applicable_{run}.csv",tc,tr);mc=common.IDENTITY+["sample_index","trace_phase","phase_index","cpu_live_heap_bytes","rss_bytes","gpu_used_bytes"];mem=[]
 for dev,trace in(("CPU",raw["cpu_trace"]),("GPU",raw["gpu_trace"])):
  for x in trace:z=ident(a,c,h,s,run,case,dev,st,ec);z.update({"sample_index":"0","trace_phase":x["phase"],"phase_index":str(x["phase_index"]),"cpu_live_heap_bytes":str(x["heap"]["bytes"])if x["heap"]["available"]else"NA","rss_bytes":str(x["rss"]["bytes"])if x["rss"]["available"]else"NA","gpu_used_bytes":str(x["gpu"]["bytes"])if x["gpu"]["available"]else"NA"});mem.append(z)
 common.write_csv(d/"operator_filtering_detrend_memory_trace_not_applicable.csv",mc,mem);ev={"run_id":run,"case_id":case,"operator_name":"detrend","requested_dtype":dtype,"dtype_semantics":"actual_typed_array_input","typed_input_count":"1","typed_input_manifest":raw["typed_input_manifest"],"actual_input_digest":raw["actual_input_digest"],"compute_dtype":"FP32","fft_dtype":"not_applicable","output_dtype":p["output_dtype"],"status":st,"error_code":ec};common.write_csv(d/f"operator_dtype_evidence_detrend_not_applicable_{run}.csv",list(ev),[ev]);rep={"run_id":run,"case_id":case,"operator_name":"detrend","scale_id":s["scale_id"],"requested_dtype":dtype,"output_dtype":p["output_dtype"],"backend":"not_applicable","mode":p["mode"],"axis":p["axis"],"breakpoints":p["breakpoints"],"rank":len(shape),"warmup_runs":w,"measured_runs":n,**{x:raw[x]for x in("mse","rmse","relative_l2","relative_linf")},"status":st,"error_code":ec};(d/"operator_detrend_report.json").write_text(json.dumps(rep,indent=2)+"\n");(d/"operator_detrend_summary.txt").write_text("\n".join(f"{k}={v}"for k,v in rep.items())+"\n");log.write_text(log.read_text()+json.dumps(rep)+"\n");print(f"REMAINING_OPERATOR_CASE_DETREND_CASE {st} scale={s['scale_id']} dtype={dtype} measured={n} results={d}");return 0 if passed else 3
if __name__=="__main__":
 try:sys.exit(main())
 except Exception as e:print(e,file=sys.stderr);sys.exit(2)
