#include "accuracy.h"
#include <cusignal/runtime/cuda_utils.h>
#include "memory.h"
#include <cusignal/operators/radartools/radartools_typed.h>
#include "sha256.h"
#include <cuda_fp16.h>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>

#ifndef ZKX_OPERATOR_CASE_RADAR_OPERATOR
#error "ZKX_OPERATOR_CASE_RADAR_OPERATOR is required"
#endif

namespace {
namespace fs=std::filesystem;
constexpr const char* kOperator=ZKX_OPERATOR_CASE_RADAR_OPERATOR;
struct Cli{std::string dtype;int n0,n1,nt,nfft,reference;double pfa,fs_hz,prf_hz;std::size_t warm,measured;fs::path output;};
struct Phase{std::string name;int index;zkx::common::ResourceSample heap,rss,gpu;};
struct Evidence{std::vector<double> cpu,gpu,cpu_ms,gpu_ms;std::vector<std::int64_t> cpu_discrete,gpu_discrete;std::vector<Phase> cpu_trace,gpu_trace;std::string manifest,input_digest,cpu_digest,gpu_digest,output_dtype;bool semantic_check{true};};

Cli parse_cli(int argc,char**argv){std::map<std::string,std::string>v;for(int i=1;i<argc;i+=2){if(i+1>=argc)throw std::invalid_argument("missing CLI value");v.emplace(std::string(argv[i]).substr(2),argv[i+1]);}auto get=[&](const char*k,const char*d=nullptr){auto i=v.find(k);if(i!=v.end())return i->second;if(d)return std::string(d);throw std::invalid_argument(std::string("missing --")+k);};return{get("dtype"),std::stoi(get("n0","1")),std::stoi(get("n1","1")),std::stoi(get("template","1")),std::stoi(get("nfft","1")),std::stoi(get("reference","1")),std::stod(get("pfa","1")),std::stod(get("fs","1")),std::stod(get("prf","1")),std::stoull(get("warmup")),std::stoull(get("measured")),get("output")};}
zkx::common::ResourceSample gpu_sample(){return zkx::common::sample_gpu_used([]{auto x=cusignal::cuda_utils::current_memory_info();return static_cast<std::int64_t>(x.total_bytes-x.free_bytes);},"cudaMemGetInfo.total_minus_free");}
Phase phase(const char*n,int i,bool gpu){return{n,i,zkx::common::sample_cpu_heap(),zkx::common::sample_cpu_rss(),gpu?gpu_sample():zkx::common::ResourceSample{false,0,"NA","CPU phase"}};}
template<class T>T convert(float x){return static_cast<T>(x);}template<>__half convert<__half>(float x){return __float2half_rn(x);}
template<class T>std::vector<T> real_input(std::size_t n,int seed){std::vector<T>v(n);for(std::size_t i=0;i<n;++i){const int z=static_cast<int>((i*17+seed)%19)-9;v[i]=convert<T>(std::is_integral_v<T>?static_cast<float>(z):z*.125f+static_cast<float>(i%7)*.03125f);}return v;}
template<class T>std::vector<cusignal::TypedComplex<T>> complex_input(std::size_t n,int seed){std::vector<cusignal::TypedComplex<T>>v(n);for(std::size_t i=0;i<n;++i){const int a=static_cast<int>((i*13+seed)%11)-5,b=static_cast<int>((i*7+seed)%9)-4;v[i]={convert<T>(std::is_integral_v<T>?static_cast<float>(a):a*.25f),convert<T>(std::is_integral_v<T>?static_cast<float>(b):b*.25f)};}return v;}
template<class T>std::string digest(const std::vector<T>&v){return zkx::remaining_operator_case::sha256_hex(std::string(reinterpret_cast<const char*>(v.data()),v.size()*sizeof(T)));}
std::string digest(const std::vector<double>&v){return zkx::remaining_operator_case::sha256_hex(std::string(reinterpret_cast<const char*>(v.data()),v.size()*sizeof(double)));}
std::vector<double> flatten(const cusignal::RadarComplexCpuResult&r){std::vector<double>v;if(r.is_fp64){for(auto z:r.fp64){v.push_back(z.re);v.push_back(z.im);}}else for(auto z:r.fp32){v.push_back(z.re);v.push_back(z.im);}return v;}
std::vector<double> flatten(const cusignal::RadarComplexDeviceResult&r){std::vector<double>v;if(r.is_fp64){for(auto z:r.fp64.to_host()){v.push_back(z.re);v.push_back(z.im);}}else for(auto z:r.fp32.to_host()){v.push_back(z.re);v.push_back(z.im);}return v;}
std::vector<double> flatten(const cusignal::AmbgfunCpuResult&r){return r.dtype==cusignal::AmbgfunOutputDtype::fp64?r.fp64:std::vector<double>(r.fp32.begin(),r.fp32.end());}
std::vector<double> flatten(const cusignal::AmbgfunDeviceResult&r){if(r.dtype==cusignal::AmbgfunOutputDtype::fp64)return r.fp64.to_host();auto x=r.fp32.to_host();return std::vector<double>(x.begin(),x.end());}
template<class F>std::vector<double> measure(std::size_t warm,std::size_t count,F f){for(std::size_t i=0;i<warm;++i)f();std::vector<double>v;v.reserve(count);for(std::size_t i=0;i<count;++i){auto a=std::chrono::steady_clock::now();f();auto b=std::chrono::steady_clock::now();v.push_back(std::chrono::duration<double,std::milli>(b-a).count());}return v;}
void emit_samples(std::ostream&o,const std::vector<double>&v){o<<'[';for(std::size_t i=0;i<v.size();++i){if(i)o<<',';o<<std::setprecision(17)<<v[i];}o<<']';}
void emit_resource(std::ostream&o,const zkx::common::ResourceSample&s){o<<"{\"available\":"<<(s.available?"true":"false")<<",\"bytes\":"<<(s.available?std::to_string(s.bytes):"null")<<'}';}
void emit_trace(std::ostream&o,const std::vector<Phase>&v){o<<'[';for(std::size_t i=0;i<v.size();++i){if(i)o<<',';o<<"{\"phase\":\""<<v[i].name<<"\",\"phase_index\":"<<v[i].index<<",\"heap\":";emit_resource(o,v[i].heap);o<<",\"rss\":";emit_resource(o,v[i].rss);o<<",\"gpu\":";emit_resource(o,v[i].gpu);o<<'}';}o<<']';}

template<class T>Evidence run(const Cli&c){Evidence e;const std::string op=kOperator;auto cpu_phases=[&](auto allocate,auto execute,auto copy,auto release){e.cpu_trace.push_back(phase("before",0,false));allocate();e.cpu_trace.push_back(phase("allocate",1,false));e.cpu_trace.push_back(phase("h2d",2,false));execute();e.cpu_trace.push_back(phase("execute_sync",3,false));copy();e.cpu_trace.push_back(phase("d2h",4,false));release();e.cpu_trace.push_back(phase("release_sync",5,false));e.cpu_trace.push_back(phase("after",6,false));};
if(op=="pulse_compression"){
 auto x=complex_input<T>(static_cast<std::size_t>(c.n0)*c.n1,3),t=complex_input<T>(c.nt,7);cusignal::PulseCompressionOptions p;p.num_pulses=c.n0;p.samples_per_pulse=c.n1;p.nfft=c.nfft;cusignal::RadarComplexCpuResult cr;cusignal::RadarComplexDeviceResult gr;
 auto cf=[&]{cr=cusignal::pulse_compression_typed_cpu(x,t,p);e.cpu=flatten(cr);};auto gf=[&]{auto dx=cusignal::DeviceArray<cusignal::TypedComplex<T>>::from_host(x),dt=cusignal::DeviceArray<cusignal::TypedComplex<T>>::from_host(t);gr=cusignal::pulse_compression_device(dx,dt,p);e.gpu=flatten(gr);};e.cpu_ms=measure(c.warm,c.measured,cf);e.gpu_ms=measure(c.warm,c.measured,gf);
 std::vector<cusignal::TypedComplex<T>>cx,ct;cpu_phases([&]{cx=x;ct=t;},[&]{cr=cusignal::pulse_compression_typed_cpu(cx,ct,p);},[&]{e.cpu=flatten(cr);},[&]{cx.clear();ct.clear();cr={};});
 cusignal::DeviceArray<cusignal::TypedComplex<T>>dx,dt;cusignal::RadarComplexDeviceResult tr;e.gpu_trace.push_back(phase("before",0,true));e.gpu_trace.push_back(phase("allocate",1,true));dx=cusignal::DeviceArray<cusignal::TypedComplex<T>>::from_host(x);dt=cusignal::DeviceArray<cusignal::TypedComplex<T>>::from_host(t);e.gpu_trace.push_back(phase("h2d",2,true));tr=cusignal::pulse_compression_device(dx,dt,p);cusignal::cuda_utils::synchronize_stream();e.gpu_trace.push_back(phase("execute_sync",3,true));e.gpu=flatten(tr);e.gpu_trace.push_back(phase("d2h",4,true));dx={};dt={};tr={};cusignal::cuda_utils::synchronize_stream();e.gpu_trace.push_back(phase("release_sync",5,true));e.gpu_trace.push_back(phase("after",6,true));e.manifest="echo:"+c.dtype+":bytes="+std::to_string(x.size()*sizeof(x[0]))+":sha256="+digest(x)+"|waveform:"+c.dtype+":bytes="+std::to_string(t.size()*sizeof(t[0]))+":sha256="+digest(t);e.output_dtype=gr.is_fp64?"ComplexFP64":"ComplexFP32";
}else if(op=="pulse_doppler"){
 auto x=complex_input<T>(static_cast<std::size_t>(c.n0)*c.n1,11);cusignal::PulseDopplerOptions p;p.num_pulses=c.n0;p.samples_per_pulse=c.n1;p.nfft=c.nfft;cusignal::RadarComplexCpuResult cr;cusignal::RadarComplexDeviceResult gr;auto cf=[&]{cr=cusignal::pulse_doppler_typed_cpu(x,p);e.cpu=flatten(cr);};auto gf=[&]{auto dx=cusignal::DeviceArray<cusignal::TypedComplex<T>>::from_host(x);gr=cusignal::pulse_doppler_device(dx,p);e.gpu=flatten(gr);};e.cpu_ms=measure(c.warm,c.measured,cf);e.gpu_ms=measure(c.warm,c.measured,gf);std::vector<cusignal::TypedComplex<T>>cx;cpu_phases([&]{cx=x;},[&]{cr=cusignal::pulse_doppler_typed_cpu(cx,p);},[&]{e.cpu=flatten(cr);},[&]{cx.clear();cr={};});cusignal::DeviceArray<cusignal::TypedComplex<T>>dx;cusignal::RadarComplexDeviceResult tr;e.gpu_trace.push_back(phase("before",0,true));e.gpu_trace.push_back(phase("allocate",1,true));dx=cusignal::DeviceArray<cusignal::TypedComplex<T>>::from_host(x);e.gpu_trace.push_back(phase("h2d",2,true));tr=cusignal::pulse_doppler_device(dx,p);cusignal::cuda_utils::synchronize_stream();e.gpu_trace.push_back(phase("execute_sync",3,true));e.gpu=flatten(tr);e.gpu_trace.push_back(phase("d2h",4,true));dx={};tr={};cusignal::cuda_utils::synchronize_stream();e.gpu_trace.push_back(phase("release_sync",5,true));e.gpu_trace.push_back(phase("after",6,true));e.manifest="compressed:"+c.dtype+":bytes="+std::to_string(x.size()*sizeof(x[0]))+":sha256="+digest(x);e.output_dtype=gr.is_fp64?"ComplexFP64":"ComplexFP32";
}else if(op=="ambgfun"){
 auto x=complex_input<T>(c.n0,19);cusignal::AmbgfunOptions p;p.fs=c.fs_hz;p.prf=c.prf_hz;p.cut=cusignal::AmbgfunCut::two_dimensional;cusignal::AmbgfunCpuResult cr;cusignal::AmbgfunDeviceResult gr;auto cf=[&]{cr=cusignal::ambgfun_typed_cpu(x,p);e.cpu=flatten(cr);};auto gf=[&]{auto dx=cusignal::DeviceArray<cusignal::TypedComplex<T>>::from_host(x);cusignal::ambgfun_device(dx,gr,p);e.gpu=flatten(gr);};e.cpu_ms=measure(c.warm,c.measured,cf);e.gpu_ms=measure(c.warm,c.measured,gf);std::vector<cusignal::TypedComplex<T>>cx;cpu_phases([&]{cx=x;},[&]{cr=cusignal::ambgfun_typed_cpu(cx,p);},[&]{e.cpu=flatten(cr);},[&]{cx.clear();cr={};});cusignal::DeviceArray<cusignal::TypedComplex<T>>dx;cusignal::AmbgfunDeviceResult tr;e.gpu_trace.push_back(phase("before",0,true));e.gpu_trace.push_back(phase("allocate",1,true));dx=cusignal::DeviceArray<cusignal::TypedComplex<T>>::from_host(x);e.gpu_trace.push_back(phase("h2d",2,true));cusignal::ambgfun_device(dx,tr,p);cusignal::cuda_utils::synchronize_stream();e.gpu_trace.push_back(phase("execute_sync",3,true));e.gpu=flatten(tr);e.gpu_trace.push_back(phase("d2h",4,true));dx={};tr={};cusignal::cuda_utils::synchronize_stream();e.gpu_trace.push_back(phase("release_sync",5,true));e.gpu_trace.push_back(phase("after",6,true));e.manifest="waveform:"+c.dtype+":bytes="+std::to_string(x.size()*sizeof(x[0]))+":sha256="+digest(x);e.output_dtype=gr.dtype==cusignal::AmbgfunOutputDtype::fp64?"FP64":"FP32";
}else if(op=="ca_cfar"){
 auto x=real_input<T>(static_cast<std::size_t>(c.n0)*c.n1,23);std::vector<int>shape{c.n0,c.n1};cusignal::CaCfarOptions p;p.guard_cells={1,1};p.reference_cells={4,4};p.pfa=c.pfa;cusignal::CaCfarCpuResult cr;cusignal::CaCfarDeviceResult gr;auto copy_cpu=[&]{e.cpu.assign(cr.threshold.begin(),cr.threshold.end());e.cpu_discrete.assign(cr.detections.size(),0);for(std::size_t i=0;i<cr.detections.size();++i)e.cpu_discrete[i]=static_cast<std::int64_t>(cr.detections[i]);};auto cf=[&]{cr=cusignal::ca_cfar_typed_cpu(x,shape,p);copy_cpu();};auto gf=[&]{auto dx=cusignal::DeviceArray<T>::from_host(x);gr=cusignal::ca_cfar_device(dx,shape,p);auto y=gr.threshold.to_host();e.gpu.assign(y.begin(),y.end());auto d=gr.detections.to_host();e.gpu_discrete.assign(d.size(),0);for(std::size_t i=0;i<d.size();++i)e.gpu_discrete[i]=static_cast<std::int64_t>(d[i]);};e.cpu_ms=measure(c.warm,c.measured,cf);e.gpu_ms=measure(c.warm,c.measured,gf);std::vector<T>cx;cpu_phases([&]{cx=x;},[&]{cr=cusignal::ca_cfar_typed_cpu(cx,shape,p);},copy_cpu,[&]{cx.clear();cr={};});cusignal::DeviceArray<T>dx;cusignal::CaCfarDeviceResult tr;e.gpu_trace.push_back(phase("before",0,true));e.gpu_trace.push_back(phase("allocate",1,true));dx=cusignal::DeviceArray<T>::from_host(x);e.gpu_trace.push_back(phase("h2d",2,true));tr=cusignal::ca_cfar_device(dx,shape,p);cusignal::cuda_utils::synchronize_stream();e.gpu_trace.push_back(phase("execute_sync",3,true));{auto y=tr.threshold.to_host();e.gpu.assign(y.begin(),y.end());auto d=tr.detections.to_host();e.gpu_discrete.assign(d.size(),0);for(std::size_t i=0;i<d.size();++i)e.gpu_discrete[i]=static_cast<std::int64_t>(d[i]);}e.gpu_trace.push_back(phase("d2h",4,true));dx={};tr={};cusignal::cuda_utils::synchronize_stream();e.gpu_trace.push_back(phase("release_sync",5,true));e.gpu_trace.push_back(phase("after",6,true));e.manifest="power:"+c.dtype+":bytes="+std::to_string(x.size()*sizeof(T))+":sha256="+digest(x);e.output_dtype="FP32+BOOL";
}else if(op=="cfar_alpha"){
 T p=convert<T>(static_cast<float>(c.pfa));cusignal::DeviceArray<double>gr;auto cf=[&]{e.cpu={cusignal::cfar_alpha_typed_cpu(p,c.reference)};};auto gf=[&]{gr=cusignal::cfar_alpha_device(p,c.reference);e.gpu=gr.to_host();};e.cpu_ms=measure(c.warm,c.measured,cf);e.gpu_ms=measure(c.warm,c.measured,gf);cpu_phases([&]{},cf,[&]{},[&]{});e.gpu_trace.push_back(phase("before",0,true));e.gpu_trace.push_back(phase("allocate",1,true));e.gpu_trace.push_back(phase("h2d",2,true));gr=cusignal::cfar_alpha_device(p,c.reference);cusignal::cuda_utils::synchronize_stream();e.gpu_trace.push_back(phase("execute_sync",3,true));e.gpu=gr.to_host();e.gpu_trace.push_back(phase("d2h",4,true));gr={};cusignal::cuda_utils::synchronize_stream();e.gpu_trace.push_back(phase("release_sync",5,true));e.gpu_trace.push_back(phase("after",6,true));std::vector<T>pv{p};e.manifest="pfa:"+c.dtype+":bytes="+std::to_string(sizeof(T))+":sha256="+digest(pv)+"|reference="+std::to_string(c.reference);e.output_dtype="FP64";
}else throw std::invalid_argument("unsupported compiled operator");
if(op=="ca_cfar"){const auto binary=[](const std::vector<std::int64_t>&v){for(const auto x:v)if(x!=0&&x!=1)return false;return true;};e.semantic_check=e.cpu.size()==e.gpu.size()&&e.cpu.size()==e.cpu_discrete.size()&&e.cpu_discrete.size()==e.gpu_discrete.size()&&binary(e.cpu_discrete)&&binary(e.gpu_discrete);}e.input_digest=zkx::remaining_operator_case::sha256_hex(e.manifest);e.cpu_digest=digest(e.cpu);e.gpu_digest=digest(e.gpu);return e;}

int dispatch(const Cli&c,Evidence&e){if(c.dtype=="FP32")e=run<float>(c);else if(c.dtype=="FP16")e=run<__half>(c);else if(c.dtype=="INT32")e=run<std::int32_t>(c);else if(c.dtype=="INT16")e=run<std::int16_t>(c);else if(c.dtype=="INT8")e=run<std::int8_t>(c);else return 2;return 0;}
}

int main(int argc,char**argv){try{const Cli c=parse_cli(argc,argv);Evidence e;if(dispatch(c,e)!=0)return 2;const auto a=zkx::common::compare(e.cpu,e.gpu,1e-12);auto d=zkx::common::compare_discrete(e.cpu_discrete,e.gpu_discrete);if(fs::exists(c.output))throw std::runtime_error("output exists");std::ofstream o(c.output);o<<"{\"operator\":\""<<kOperator<<"\",\"requested_dtype\":\""<<c.dtype<<"\",\"output_dtype\":\""<<e.output_dtype<<"\",\"typed_input_manifest\":\""<<e.manifest<<"\",\"actual_input_digest\":\""<<e.input_digest<<"\",\"cpu_output_digest\":\""<<e.cpu_digest<<"\",\"gpu_output_digest\":\""<<e.gpu_digest<<"\",\"mse\":"<<a.mse<<",\"rmse\":"<<a.rmse<<",\"relative_l2\":"<<a.relative_l2<<",\"relative_linf\":"<<a.relative_linf<<",\"exact_match\":"<<(d.exact?"true":"false")<<",\"mismatch_count\":"<<d.mismatch_count<<",\"semantic_check\":"<<(e.semantic_check?"true":"false")<<",\"cpu_samples_ms\":";emit_samples(o,e.cpu_ms);o<<",\"gpu_samples_ms\":";emit_samples(o,e.gpu_ms);o<<",\"cpu_trace\":";emit_trace(o,e.cpu_trace);o<<",\"gpu_trace\":";emit_trace(o,e.gpu_trace);o<<"}\n";std::cout<<"OPERATOR_CASE_RADAR_PROBE PASS operator="<<kOperator<<" dtype="<<c.dtype<<'\n';return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}}
