#include "accuracy.h"
#include <cusignal/runtime/cuda_utils.h>
#include <cusignal/operators/filtering/filtering_typed.h>
#include "memory.h"
#include "sha256.h"
#include <cuda_fp16.h>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>
namespace {namespace fs=std::filesystem;
struct Cli{std::string dtype;int order{},leading{};std::uint64_t seed{};std::size_t warmup{},measured{};fs::path output;};struct Phase{std::string name;int index{};zkx::common::ResourceSample heap,rss,gpu;};
Cli cli(int argc,char**argv){std::map<std::string,std::string>v;for(int i=1;i<argc;i+=2){if(i+1>=argc||std::string(argv[i]).rfind("--",0))throw std::invalid_argument("args");v.emplace(std::string(argv[i]).substr(2),argv[i+1]);}auto g=[&](const char*k)->const std::string&{auto i=v.find(k);if(i==v.end())throw std::invalid_argument(k);return i->second;};Cli c{g("dtype"),std::stoi(g("order")),std::stoi(g("leading")),std::stoull(g("seed")),std::stoull(g("warmup")),std::stoull(g("measured")),g("output")};if(v.size()!=7||c.order<1||(c.leading!=0&&c.leading!=1)||!c.warmup||!c.measured)throw std::invalid_argument("invalid");return c;}
zkx::common::ResourceSample gpu_sample(){return zkx::common::sample_gpu_used([]{auto i=cusignal::cuda_utils::current_memory_info();return static_cast<std::int64_t>(i.total_bytes-i.free_bytes);},"cudaMemGetInfo.total_minus_free");}Phase phase(const char*n,int i,bool gpu){return{n,i,zkx::common::sample_cpu_heap(),zkx::common::sample_cpu_rss(),gpu?gpu_sample():zkx::common::ResourceSample{false,0,"NA","CPU"}};}
template<class T>T cast(float x){return static_cast<T>(x);}template<>__half cast<__half>(float x){return __float2half_rn(x);}template<class T>void coefficients(int order,int leading,std::vector<T>&b,std::vector<T>&a){b.assign(order+1,cast<T>(0));a.assign(order+1+leading,cast<T>(0));b[0]=cast<T>(1);a[leading]=cast<T>(2);a[leading+1]=cast<T>(-1);}
template<class T>std::string digest(const std::vector<T>&v){return zkx::remaining_operator_case::sha256_hex(std::string(reinterpret_cast<const char*>(v.data()),v.size()*sizeof(T)));}template<class F>std::vector<double>measure(std::size_t w,std::size_t n,F&&f){for(std::size_t i=0;i<w;++i)f();std::vector<double>s;for(std::size_t i=0;i<n;++i){auto a=std::chrono::steady_clock::now();f();auto b=std::chrono::steady_clock::now();s.push_back(std::chrono::duration<double,std::milli>(b-a).count());}return s;}void samples(std::ostream&o,const std::vector<double>&v){o<<'[';for(std::size_t i=0;i<v.size();++i){if(i)o<<',';o<<std::setprecision(17)<<v[i];}o<<']';}void resource(std::ostream&o,const zkx::common::ResourceSample&s){o<<"{\"available\":"<<(s.available?"true":"false")<<",\"bytes\":"<<(s.available?std::to_string(s.bytes):"null")<<'}';}void phases(std::ostream&o,const std::vector<Phase>&v){o<<'[';for(std::size_t i=0;i<v.size();++i){if(i)o<<',';o<<"{\"phase\":\""<<v[i].name<<"\",\"phase_index\":"<<v[i].index<<",\"heap\":";resource(o,v[i].heap);o<<",\"rss\":";resource(o,v[i].rss);o<<",\"gpu\":";resource(o,v[i].gpu);o<<'}';}o<<']';}
template<class T>int run(const Cli&c){std::vector<T>b,a;coefficients(c.order,c.leading,b,a);std::vector<double>cpu_output,gpu_output;auto cpu=measure(c.warmup,c.measured,[&]{cpu_output=cusignal::lfilter_zi_typed_cpu(b,a);});auto gpu=measure(c.warmup,c.measured,[&]{auto db=cusignal::DeviceArray<T>::from_host(b);auto da=cusignal::DeviceArray<T>::from_host(a);cusignal::LfilterZiDeviceResult out;cusignal::lfilter_zi_device(db,da,out);gpu_output=out.fp64.to_host();});
std::vector<Phase>ct{phase("before",0,false),phase("allocate",1,false),phase("h2d",2,false)};auto tc=cusignal::lfilter_zi_typed_cpu(b,a);ct.push_back(phase("execute_sync",3,false));ct.push_back(phase("d2h",4,false));tc.clear();tc.shrink_to_fit();ct.push_back(phase("release_sync",5,false));ct.push_back(phase("after",6,false));std::vector<Phase>gt;cusignal::cuda_utils::synchronize_stream();gt.push_back(phase("before",0,true));cusignal::LfilterZiDeviceResult tg;gt.push_back(phase("allocate",1,true));auto db=cusignal::DeviceArray<T>::from_host(b);auto da=cusignal::DeviceArray<T>::from_host(a);gt.push_back(phase("h2d",2,true));cusignal::lfilter_zi_device(db,da,tg);cusignal::cuda_utils::synchronize_stream();gt.push_back(phase("execute_sync",3,true));auto th=tg.fp64.to_host();gt.push_back(phase("d2h",4,true));tg={};db={};da={};th.clear();th.shrink_to_fit();cusignal::cuda_utils::synchronize_stream();gt.push_back(phase("release_sync",5,true));gt.push_back(phase("after",6,true));auto ac=zkx::common::compare(cpu_output,gpu_output,1e-12);if(!std::isfinite(ac.mse)||!std::isfinite(ac.rmse)||!std::isfinite(ac.relative_l2)||!std::isfinite(ac.relative_linf))throw std::runtime_error("nonfinite accuracy metric");
std::string manifest="b:"+c.dtype+":["+std::to_string(b.size())+"]:bytes="+std::to_string(b.size()*sizeof(T))+":sha256="+digest(b)+"|a:"+c.dtype+":["+std::to_string(a.size())+"]:bytes="+std::to_string(a.size()*sizeof(T))+":sha256="+digest(a);std::string input_digest=zkx::remaining_operator_case::sha256_hex(manifest);if(fs::exists(c.output))throw std::runtime_error("exists");std::ofstream o(c.output);o<<"{\"schema_version\":1,\"operator_name\":\"lfilter_zi\",\"backend\":\"not_applicable\",\"requested_dtype\":\""<<c.dtype<<"\",\"compute_dtype\":\"FP32\",\"fft_dtype\":\"not_applicable\",\"output_dtype\":\"FP64\",\"state_order\":"<<c.order<<",\"leading_denominator_zeros\":"<<c.leading<<",\"scientific_work_units\":"<<c.order*c.order*c.order<<",\"output_count\":"<<cpu_output.size()<<",\"typed_input_count\":2,\"typed_input_manifest\":\""<<manifest<<"\",\"actual_input_digest\":\""<<input_digest<<"\",\"cpu_output_digest\":\""<<digest(cpu_output)<<"\",\"gpu_output_digest\":\""<<digest(gpu_output)<<"\",\"mse\":"<<std::setprecision(17)<<ac.mse<<",\"rmse\":"<<ac.rmse<<",\"relative_l2\":"<<ac.relative_l2<<",\"relative_linf\":"<<ac.relative_linf<<",\"cpu_samples_ms\":";samples(o,cpu);o<<",\"gpu_samples_ms\":";samples(o,gpu);o<<",\"cpu_trace\":";phases(o,ct);o<<",\"gpu_trace\":";phases(o,gt);o<<"}\n";std::cout<<"REMAINING_OPERATOR_CASE_LFILTER_ZI_PROBE PASS dtype="<<c.dtype<<" backend=not_applicable\n";return 0;}}
int main(int argc,char**argv){try{auto c=cli(argc,argv);if(c.dtype=="FP32")return run<float>(c);if(c.dtype=="FP16")return run<__half>(c);if(c.dtype=="INT32")return run<std::int32_t>(c);if(c.dtype=="INT16")return run<std::int16_t>(c);if(c.dtype=="INT8")return run<std::int8_t>(c);throw std::invalid_argument("dtype");}catch(const std::exception&e){std::cerr<<"REMAINING_OPERATOR_CASE_LFILTER_ZI_PROBE FAIL error="<<e.what()<<'\n';return 2;}}
