function fig2_task1_flow()
    config = plot_common();
    
    fig = figure('Position', [100, 100, config.figure_width*100, config.figure_height*100]);
    set(fig, 'Color', 'white');
    
    ax = axes('Parent', fig);
    set(ax, 'Visible', 'off');
    set(ax, 'XLim', [0 100]);
    set(ax, 'YLim', [0 100]);
    
    box_width = 15;
    box_height = 8;
    
    steps = {'输入数据', 'FFT处理', '多普勒分析', 'CFAR检测', '输出目标'};
    x_positions = [10, 28, 46, 64, 82];
    y_pos = 46;
    
    colors = [0.25 0.41 0.88; 0.58 0.40 0.74; 0.15 0.68 0.38; 0.93 0.69 0.13; 0.85 0.33 0.10];
    
    for i = 1:length(steps)
        pos = [x_positions(i), y_pos, box_width, box_height];
        draw_box(ax, pos, colors(i,:), steps{i});
    end
    
    for i = 1:length(steps)-1
        x1 = x_positions(i) + box_width;
        x2 = x_positions(i+1);
        y = y_pos + box_height/2;
        draw_arrow(fig, x1, y, x2, y);
    end
    
    details = {'原始IQ数据', '快速傅里叶变换', '多普勒谱估计', '恒虚警率检测', '目标坐标与速度'};
    for i = 1:length(details)
        text(x_positions(i) + box_width/2, y_pos - 8, details{i}, ...
            'Parent', ax, ...
            'HorizontalAlignment', 'center', ...
            'FontSize', 10, ...
            'FontName', 'Microsoft YaHei', ...
            'Color', [0.5 0.5 0.5]);
    end
    
    annotation(fig, 'textbox', [0.05, 0.05, 0.9, 0.05], ...
        'String', '测试环境: ZQ500 GPU | Task1: 雷达目标检测与多普勒分析 | 统计次数: 100', ...
        'FontSize', config.font_size_small, ...
        'FontName', config.font_name, ...
        'EdgeColor', 'none', ...
        'HorizontalAlignment', 'center');
end

function draw_box(ax, pos, color, text_str)
    x = pos(1);
    y = pos(2);
    w = pos(3);
    h = pos(4);
    
    rectangle('Parent', ax, ...
        'Position', [x, y, w, h], ...
        'FaceColor', color, ...
        'EdgeColor', 'black', ...
        'LineWidth', 1.5);
    
    text(x + w/2, y + h/2, text_str, ...
        'Parent', ax, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontSize', 12, ...
        'FontName', 'Microsoft YaHei', ...
        'Color', 'white');
end

function draw_arrow(fig, x1, y1, x2, y2)
    annotation(fig, 'arrow', ...
        [x1/100, x2/100], ...
        [y1/100, y2/100], ...
        'LineWidth', 1.5, ...
        'Color', [0.3 0.3 0.3]);
end