#include "accuracy.h"
#include <cusignal/operators/bsplines/bsplines_typed.h>
#include <cusignal/runtime/cuda_utils.h>
#include "memory.h"
#include "sha256.h"
#include <cuda_fp16.h>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>
namespace{namespace fs=std::filesystem;struct C{std::string op,dt;int n,order;uint64_t seed;size_t warm,measured;fs::path out;};struct P{std::string n;int i;zkx::common::ResourceSample h,r,g;};C cli(int n,char**a){std::map<std::string,std::string>v;for(int i=1;i<n;i+=2)v.emplace(std::string(a[i]).substr(2),a[i+1]);auto g=[&](const char*k)->const std::string&{auto x=v.find(k);if(x==v.end())throw std::invalid_argument(k);return x->second;};return{g("operator"),g("dtype"),std::stoi(g("elements")),std::stoi(g("order")),std::stoull(g("seed")),std::stoull(g("warmup")),std::stoull(g("measured")),g("output")};}zkx::common::ResourceSample gs(){return zkx::common::sample_gpu_used([]{auto i=cusignal::cuda_utils::current_memory_info();return(int64_t)(i.total_bytes-i.free_bytes);},"cudaMemGetInfo.total_minus_free");}P ph(const char*n,int i,bool g){return{n,i,zkx::common::sample_cpu_heap(),zkx::common::sample_cpu_rss(),g?gs():zkx::common::ResourceSample{false,0,"NA","CPU"}};}template<class T>T cv(float x){return(T)x;}template<>__half cv<__half>(float x){return __float2half_rn(x);}template<class T>double dv(T x){return(double)x;}template<>double dv(__half x){return __half2float(x);}template<class T>std::vector<T>input(int n,uint64_t s){std::vector<T>v;v.reserve(n);for(int i=0;i<n;i++){float x=std::is_integral_v<T>?float((i+int(s%5))%7-3):float((i%257)-128)/32.0f+float(s%3)/16.0f;v.push_back(cv<T>(x));}return v;}template<class T>std::string dg(const std::vector<T>&v){return zkx::remaining_operator_case::sha256_hex(std::string((const char*)v.data(),v.size()*sizeof(T)));}template<class T>std::vector<double>flat(const std::vector<T>&v){std::vector<double>o;o.reserve(v.size());for(auto x:v)o.push_back(dv(x));return o;}template<class F>std::vector<double>meas(size_t w,size_t n,F f){for(size_t i=0;i<w;i++)f();std::vector<double>v;for(size_t i=0;i<n;i++){auto a=std::chrono::steady_clock::now();f();auto b=std::chrono::steady_clock::now();v.push_back(std::chrono::duration<double,std::milli>(b-a).count());}return v;}void ss(std::ostream&o,const std::vector<double>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<std::setprecision(17)<<v[i];}o<<']';}void rs(std::ostream&o,const zkx::common::ResourceSample&s){o<<"{\"available\":"<<(s.available?"true":"false")<<",\"bytes\":"<<(s.available?std::to_string(s.bytes):"null")<<'}';}void ps(std::ostream&o,const std::vector<P>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<"{\"phase\":\""<<v[i].n<<"\",\"phase_index\":"<<v[i].i<<",\"heap\":";rs(o,v[i].h);o<<",\"rss\":";rs(o,v[i].r);o<<",\"gpu\":";rs(o,v[i].g);o<<'}';}o<<']';}
template<class T>int run(const C&c){auto x=input<T>(c.n,c.seed);std::vector<T>cr,gr;auto cpu=[&]{cr=c.op=="gauss_spline"?cusignal::gauss_spline_cpu(x,c.order):cusignal::quadratic_cpu(x);};auto gpu=[&]{auto dx=cusignal::DeviceArray<T>::from_host(x);cusignal::DeviceArray<T>o(c.n);if(c.op=="gauss_spline")cusignal::gauss_spline_device(dx,o,c.order);else cusignal::quadratic_device(dx,o);gr=o.to_host();};auto ct=meas(c.warm,c.measured,cpu),gt=meas(c.warm,c.measured,gpu);std::vector<P>cp;cp.push_back(ph("before",0,0));auto hx=x;cp.push_back(ph("allocate",1,0));cp.push_back(ph("h2d",2,0));auto co=c.op=="gauss_spline"?cusignal::gauss_spline_cpu(hx,c.order):cusignal::quadratic_cpu(hx);cp.push_back(ph("execute_sync",3,0));auto ch=flat(co);cp.push_back(ph("d2h",4,0));hx.clear();co.clear();ch.clear();cp.push_back(ph("release_sync",5,0));cp.push_back(ph("after",6,0));std::vector<P>gp;cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("before",0,1));cusignal::DeviceArray<T>go(c.n);gp.push_back(ph("allocate",1,1));auto dx=cusignal::DeviceArray<T>::from_host(x);gp.push_back(ph("h2d",2,1));if(c.op=="gauss_spline")cusignal::gauss_spline_device(dx,go,c.order);else cusignal::quadratic_device(dx,go);cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("execute_sync",3,1));auto gh=go.to_host();gp.push_back(ph("d2h",4,1));go={};dx={};gh.clear();cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("release_sync",5,1));gp.push_back(ph("after",6,1));auto cvv=flat(cr),gv=flat(gr);auto ac=zkx::common::compare(cvv,gv,1e-12);std::string man="x:"+c.dt+":["+std::to_string(x.size())+"]:bytes="+std::to_string(x.size()*sizeof(T))+":sha256="+dg(x),id=zkx::remaining_operator_case::sha256_hex(man);if(fs::exists(c.out))throw std::runtime_error("exists");std::ofstream o(c.out);o<<"{\"operator_name\":\""<<c.op<<"\",\"requested_dtype\":\""<<c.dt<<"\",\"output_dtype\":\""<<c.dt<<"\",\"backend\":\"not_applicable\",\"input_count\":"<<c.n<<",\"output_count\":"<<cr.size()<<",\"order\":"<<c.order<<",\"typed_input_manifest\":\""<<man<<"\",\"actual_input_digest\":\""<<id<<"\",\"cpu_output_digest\":\""<<dg(cr)<<"\",\"gpu_output_digest\":\""<<dg(gr)<<"\",\"mse\":"<<ac.mse<<",\"rmse\":"<<ac.rmse<<",\"relative_l2\":"<<ac.relative_l2<<",\"relative_linf\":"<<ac.relative_linf<<",\"cpu_samples_ms\":";ss(o,ct);o<<",\"gpu_samples_ms\":";ss(o,gt);o<<",\"cpu_trace\":";ps(o,cp);o<<",\"gpu_trace\":";ps(o,gp);o<<"}\n";return 0;}int main_t(const C&c){if(c.dt=="FP32")return run<float>(c);if(c.dt=="FP16")return run<__half>(c);if(c.dt=="INT32")return run<int32_t>(c);if(c.dt=="INT16")return run<int16_t>(c);if(c.dt=="INT8")return run<int8_t>(c);return 2;}}
int main(int n,char**a){try{return main_t(cli(n,a));}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}}
