function fig3_2_consistency_matrix()
[outDir, palette] = SupportFiguresCommon.init();

[modules, funcs, cpuLevel, callStyle, fftFlag] = localOperatorData();
n = numel(funcs);

% Columns are deliberately explicit: each tick is a concrete compatibility
% or accuracy layer, not a generic implementation name.
colLabels = { ...
    'Python参考接口', ...
    'C++ CPU接口对齐', ...
    'Host/Python精度', ...
    'GPU _device入口', ...
    'Device主路径数值', ...
    'FFT B/C一致性'};

status = zeros(n, numel(colLabels));
status(:,1) = 3;                 % Present in cusignal-23.08.00 reference set.
status(:,2) = cpuLevel;          % 3 = high alignment, 2 = medium alignment.
status(:,3) = 3;                 % compare_results.py: 235 / 235 PASS.
status(:,4) = 3;                 % 53 / 53 Device API implemented.
status(:,5) = 3;                 % test_all_signals covers CPU/device main paths.
status(:,6) = fftFlag;           % 3 = covered, 2 = partial FFT path, 0 = N/A.

fig = figure('Color','w','Position',[80 40 1500 1180]);
tiledlayout(fig, 1, 2, 'TileSpacing','compact', 'Padding','compact');

ax = nexttile(1);
imagesc(ax, status);
colormap(ax, [ ...
    0.92 0.92 0.92; ...
    palette.lightOrange; ...
    palette.orange; ...
    palette.green]);
caxis(ax, [0 3]);

set(ax, ...
    'XTick', 1:numel(colLabels), ...
    'XTickLabel', colLabels, ...
    'YTick', 1:n, ...
    'YTickLabel', funcs, ...
    'TickLength', [0 0], ...
    'XAxisLocation', 'top', ...
    'XLim', [0.02 numel(colLabels)+0.5], ...
    'YLim', [0.5 n+0.5], ...
    'FontSize', 8.5);
xtickangle(ax, 24);
xlabel(ax, '接口/精度检查口径');
ylabel(ax, '53个具体 public API');
title(ax, 'a  接口与精度一致性矩阵：按函数展开', 'FontSize', 14, 'FontWeight', 'bold');
grid(ax, 'on');
set(ax, 'GridColor', [1 1 1], 'GridAlpha', 1, 'LineWidth', 1.0);

for r = 1:n
    for c = 1:numel(colLabels)
        label = localStatusLabel(status(r,c), c, cpuLevel(r), callStyle{r});
        if status(r,c) == 3
            txtColor = [1 1 1];
        elseif status(r,c) == 2
            txtColor = [0.20 0.20 0.20];
        else
            txtColor = [0.42 0.42 0.42];
        end
        text(ax, c, r, label, ...
            'HorizontalAlignment','center', ...
            'FontSize', 6.6, ...
            'FontWeight','bold', ...
            'Color', txtColor);
    end
end

hold(ax, 'on');
moduleNames = unique(modules, 'stable');
for i = 1:numel(moduleNames)
    rows = find(strcmp(modules, moduleNames{i}));
    yMid = mean(rows);
    text(ax, 0.34, yMid, moduleNames{i}, ...
        'HorizontalAlignment','right', ...
        'FontSize', 8.0, ...
        'FontWeight','bold', ...
        'Color', palette.gray);
    ySep = rows(end) + 0.5;
    plot(ax, [0.5 numel(colLabels)+0.5], [ySep ySep], 'Color', [1 1 1], 'LineWidth', 1.2);
end
hold(ax, 'off');

ax2 = nexttile(2);
axis(ax2, 'off');
xlim(ax2, [0 1]);
ylim(ax2, [0 1]);
title(ax2, 'b  Tick含义与覆盖摘要', 'FontSize', 14, 'FontWeight', 'bold');

summaryLines = { ...
    '数据来源：cusignal-23.08.00 / ZKX/cusignal_cpp / ZKX/cusignal_cpp_gpu', ...
    'Python参考接口：该函数属于 cuSignal 23.08 对齐函数集合', ...
    'C++ CPU接口对齐：高=基本按 Python/cusignal 心智迁移；中=语义对齐但需看 C++ 参数/返回约定', ...
    'Host/Python精度：compare_results.py 全局回归 235/235 PASS', ...
    'GPU _device入口：ZKX/cusignal_cpp_gpu 已有显式 Device API', ...
    'Device主路径数值：test_all_signals 中已有 CPU/device 主路径对照', ...
    'FFT B/C一致性：仅 FFT-based 或 partial FFT path 需要；非 FFT 函数标为 N/A'};

y = 0.93;
for i = 1:numel(summaryLines)
    text(ax2, 0.02, y, summaryLines{i}, ...
        'FontSize', 10.4, ...
        'Color', [0.18 0.18 0.18], ...
        'Interpreter','none');
    y = y - 0.058;
end

legendY = 0.48;
legendItems = { ...
    'YES / PASS / 高 / FFT', palette.green; ...
    '中 / Partial', palette.orange; ...
    'N/A', [0.92 0.92 0.92]};
for i = 1:size(legendItems,1)
    rectangle(ax2, 'Position', [0.03, legendY - 0.055*(i-1), 0.045, 0.030], ...
        'FaceColor', legendItems{i,2}, ...
        'EdgeColor', [0.30 0.30 0.30]);
    text(ax2, 0.09, legendY + 0.004 - 0.055*(i-1), legendItems{i,1}, ...
        'FontSize', 10.2, ...
        'Interpreter','none');
end

moduleCounts = zeros(numel(moduleNames),1);
for i = 1:numel(moduleNames)
    moduleCounts(i) = sum(strcmp(modules, moduleNames{i}));
end

barAx = axes('Parent', fig, 'Position', [0.735 0.075 0.235 0.23]);
barh(barAx, categorical(moduleNames), moduleCounts, 'FaceColor', palette.blue);
title(barAx, '模块覆盖数量', 'FontSize', 11);
xlabel(barAx, '函数数');
grid(barAx, 'on');
set(barAx, 'FontSize', 8.2);

SupportFiguresCommon.saveFig(fig, outDir, 'fig3_2_3_consistency_matrix');
end

function label = localStatusLabel(value, col, cpu, style)
if value == 0
    label = 'N/A';
elseif col == 2
    if cpu == 3
        label = '高';
    else
        label = '中';
    end
elseif col == 3
    label = 'PASS';
elseif col == 4
    label = style;
elseif col == 6
    if value == 3
        label = 'FFT';
    else
        label = 'Partial';
    end
else
    label = 'YES';
end
end

function [modules, funcs, cpuLevel, callStyle, fftFlag] = localOperatorData()
rows = { ...
    'bsplines','cubic',3,'simple',0; ...
    'bsplines','gauss_spline',3,'simple',0; ...
    'bsplines','quadratic',3,'simple',0; ...
    'convolution','correlate',3,'workspace',2; ...
    'convolution','correlate2d',3,'workspace',2; ...
    'demod','fm_demod',3,'shape',0; ...
    'estimation','KalmanFilter',2,'low-level',0; ...
    'filter_design','firwin',3,'simple',0; ...
    'filter_design','firwin2',3,'simple',3; ...
    'filtering','channelize_poly',3,'simple',3; ...
    'filtering','detrend',3,'shape',0; ...
    'filtering','firfilter',3,'shape',0; ...
    'filtering','firfilter2',2,'shape',0; ...
    'filtering','freq_shift',3,'simple',0; ...
    'filtering','hilbert',3,'workspace',3; ...
    'filtering','hilbert2',2,'workspace',3; ...
    'filtering','lfilter_zi',3,'simple',0; ...
    'filtering','sosfilt',3,'shape',0; ...
    'filtering','wiener',3,'shape',0; ...
    'filtering','decimate',3,'shape',0; ...
    'filtering','resample',2,'simple',2; ...
    'filtering','resample_poly',2,'params+ws',0; ...
    'filtering','upfirdn',3,'params+ws',0; ...
    'peak_finding','argrelextrema',3,'shape',0; ...
    'radartools','ambgfun',2,'params+ws',3; ...
    'radartools','ca_cfar',3,'simple',0; ...
    'radartools','cfar_alpha',3,'simple',0; ...
    'radartools','pulse_compression',2,'params+ws',3; ...
    'radartools','pulse_doppler',2,'params+ws',3; ...
    'spectral_analysis','csd',2,'params+ws',3; ...
    'spectral_analysis','istft',2,'shape',3; ...
    'spectral_analysis','lombscargle',3,'simple',0; ...
    'spectral_analysis','spectrogram',2,'params+ws',3; ...
    'spectral_analysis','stft',2,'params+ws',3; ...
    'spectral_analysis','vectorstrength',3,'simple',0; ...
    'waveforms','chirp',3,'simple',0; ...
    'waveforms','sawtooth',3,'simple',0; ...
    'waveforms','square',3,'simple',0; ...
    'waveforms','gausspulse',2,'simple',0; ...
    'waveforms','unit_impulse',2,'simple',0; ...
    'wavelets','cwt',2,'simple',0; ...
    'wavelets','morlet',3,'simple',0; ...
    'wavelets','morlet2',3,'simple',0; ...
    'wavelets','qmf',3,'simple',0; ...
    'wavelets','ricker',3,'simple',0; ...
    'windows','chebwin',3,'simple',3; ...
    'windows','general_cosine',3,'simple',0; ...
    'windows','general_gaussian',3,'simple',0; ...
    'windows','hamming',3,'simple',0; ...
    'windows','kaiser',3,'simple',0; ...
    'windows','parzen',3,'simple',0; ...
    'windows','taylor',3,'simple',0; ...
    'windows','triang',3,'simple',0};

modules = rows(:,1);
funcs = rows(:,2);
cpuLevel = cell2mat(rows(:,3));
callStyle = rows(:,4);
fftFlag = cell2mat(rows(:,5));
end
