%% generate_all_supporting_figures.m
% Current entry point. generate_supporting_figures.m is retained only as a
% historical monolithic version.
%
% By default, figure windows stay open for inspection. To auto-close them
% after export in batch mode, set environment variable:
%   SUPPORT_FIGURES_CLOSE=1

clear; close all; clc;
addpath(fileparts(mfilename('fullpath')));

figureScripts = { ...
    @fig1_1_architecture_parallel_design, ...
    @fig2_1_gpu_flow_and_dispatch, ...
    @fig2_2_operator_tree_api_status, ...
    @fig2_3_task_pipeline_encapsulation, ...
    @fig3_2_accuracy_task1_mse, ...
    @fig3_2_accuracy_task2_mse, ...
    @fig3_2_consistency_matrix, ...
    @fig3_2_output_overlay_example, ...
    @fig3_3_task1_end_to_end_mosaic, ...
    @fig3_3_task2_end_to_end_mosaic, ...
    @fig3_4_operator_performance_compare, ...
    @fig3_4_speedup_compare, ...
    @fig3_4_cpp_device_baseline, ...
    @fig3_4_cuda_optimization_before_after, ...
    @fig3_5_snr_robustness, ...
    @fig3_5_ambgfun_waveform_compare, ...
    @fig3_5_cfar_compare, ...
    @fig3_5_bspline_smoothing, ...
    @fig3_6_stability_resource_error_handling, ...
    @fig4_1_operator_coverage, ...
    @fig4_2_additional_speedup, ...
    @fig5_1_summary_dashboard ...
};

for k = 1:numel(figureScripts)
    figureScripts{k}();
end

[outDir, ~] = SupportFiguresCommon.init();
fprintf('完成。图片将导出到：%s\n', outDir);
