#include "accuracy.h"
#include <cusignal/runtime/cuda_utils.h>
#include <cusignal/operators/filtering/filtering_typed.h>
#include "memory.h"
#include "sha256.h"
#include <cuda_fp16.h>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>
namespace { namespace fs=std::filesystem;
struct Cli{std::string dtype,filter;int rows{},cols{},axis{},up{},down{};std::uint64_t seed{};std::size_t warmup{},measured{};fs::path output;};
struct Phase{std::string name;int index{};zkx::common::ResourceSample heap,rss,gpu;};
Cli cli(int argc,char**argv){std::map<std::string,std::string>v;for(int i=1;i<argc;i+=2){if(i+1>=argc||std::string(argv[i]).rfind("--",0))throw std::invalid_argument("expected --key value");v.emplace(std::string(argv[i]).substr(2),argv[i+1]);}auto g=[&](const char*k)->const std::string&{auto i=v.find(k);if(i==v.end())throw std::invalid_argument(std::string("missing --")+k);return i->second;};Cli c{g("dtype"),g("filter-mode"),std::stoi(g("rows")),std::stoi(g("cols")),std::stoi(g("axis")),std::stoi(g("up")),std::stoi(g("down")),std::stoull(g("seed")),std::stoull(g("warmup")),std::stoull(g("measured")),g("output")};if(v.size()!=11||c.rows<1||c.cols<1||c.up<1||c.down<1||!c.warmup||!c.measured)throw std::invalid_argument("invalid arguments");return c;}
zkx::common::ResourceSample gpu_sample(){return zkx::common::sample_gpu_used([]{auto i=cusignal::cuda_utils::current_memory_info();return static_cast<std::int64_t>(i.total_bytes-i.free_bytes);},"cudaMemGetInfo.total_minus_free");}
Phase phase(const char*n,int i,bool gpu){return{n,i,zkx::common::sample_cpu_heap(),zkx::common::sample_cpu_rss(),gpu?gpu_sample():zkx::common::ResourceSample{false,0,"NA","CPU path"}};}
template<class T>T cast(float x){return static_cast<T>(x);}template<>__half cast<__half>(float x){return __float2half_rn(x);}
template<class T>std::vector<T> input(std::size_t n,std::uint64_t seed){std::vector<T>v;v.reserve(n);for(std::size_t i=0;i<n;++i){int r=static_cast<int>((i*17+seed)%11)-5;v.push_back(cast<T>(std::is_integral_v<T>?float(r):float(r)*0.25f));}return v;}
template<class T>std::vector<T> taps(){return{cast<T>(1),cast<T>(2),cast<T>(3),cast<T>(2),cast<T>(1)};}
template<class T>std::string digest(const std::vector<T>&v){return zkx::remaining_operator_case::sha256_hex(std::string(reinterpret_cast<const char*>(v.data()),v.size()*sizeof(T)));}
template<class T>double val(T x){return static_cast<double>(x);}template<>double val(__half x){return __half2float(x);}
template<class T>std::vector<double> dv(const std::vector<T>&v){std::vector<double>r;r.reserve(v.size());for(auto x:v)r.push_back(val(x));return r;}
std::vector<double> cpu_values(const cusignal::ResamplePolyCpuResult&r){switch(r.dtype){case cusignal::ResamplePolyOutputDtype::fp16:return dv(r.fp16);case cusignal::ResamplePolyOutputDtype::fp32:return dv(r.fp32);case cusignal::ResamplePolyOutputDtype::fp64:return r.fp64;case cusignal::ResamplePolyOutputDtype::int32:return dv(r.int32);case cusignal::ResamplePolyOutputDtype::int16:return dv(r.int16);case cusignal::ResamplePolyOutputDtype::int8:return dv(r.int8);}throw std::runtime_error("dtype");}
std::vector<double> gpu_values(const cusignal::ResamplePolyDeviceResult&r){switch(r.dtype){case cusignal::ResamplePolyOutputDtype::fp16:return dv(r.fp16.to_host());case cusignal::ResamplePolyOutputDtype::fp32:return dv(r.fp32.to_host());case cusignal::ResamplePolyOutputDtype::fp64:return r.fp64.to_host();case cusignal::ResamplePolyOutputDtype::int32:return dv(r.int32.to_host());case cusignal::ResamplePolyOutputDtype::int16:return dv(r.int16.to_host());case cusignal::ResamplePolyOutputDtype::int8:return dv(r.int8.to_host());}throw std::runtime_error("dtype");}
std::string dtype_name(cusignal::ResamplePolyOutputDtype d){switch(d){case cusignal::ResamplePolyOutputDtype::fp16:return"FP16";case cusignal::ResamplePolyOutputDtype::fp32:return"FP32";case cusignal::ResamplePolyOutputDtype::fp64:return"FP64";case cusignal::ResamplePolyOutputDtype::int32:return"INT32";case cusignal::ResamplePolyOutputDtype::int16:return"INT16";case cusignal::ResamplePolyOutputDtype::int8:return"INT8";}return"NA";}
template<class F>std::vector<double> measure(std::size_t w,std::size_t n,F&&f){for(std::size_t i=0;i<w;++i)f();std::vector<double>s;for(std::size_t i=0;i<n;++i){auto a=std::chrono::steady_clock::now();f();auto b=std::chrono::steady_clock::now();s.push_back(std::chrono::duration<double,std::milli>(b-a).count());}return s;}
void samples(std::ostream&o,const std::vector<double>&v){o<<'[';for(std::size_t i=0;i<v.size();++i){if(i)o<<',';o<<std::setprecision(17)<<v[i];}o<<']';}void sample(std::ostream&o,const zkx::common::ResourceSample&s){o<<"{\"available\":"<<(s.available?"true":"false")<<",\"bytes\":"<<(s.available?std::to_string(s.bytes):"null")<<'}';}void phases(std::ostream&o,const std::vector<Phase>&v){o<<'[';for(std::size_t i=0;i<v.size();++i){if(i)o<<',';o<<"{\"phase\":\""<<v[i].name<<"\",\"phase_index\":"<<v[i].index<<",\"heap\":";sample(o,v[i].heap);o<<",\"rss\":";sample(o,v[i].rss);o<<",\"gpu\":";sample(o,v[i].gpu);o<<'}';}o<<']';}
template<class T>int run(const Cli&c){
 auto x=input<T>(static_cast<std::size_t>(c.rows)*c.cols,c.seed);auto h=c.filter=="custom"?taps<T>():std::vector<T>{};cusignal::ResamplePolyOptions opt;opt.shape={c.rows,c.cols};opt.axis=c.axis;opt.window_mode=cusignal::ResamplePolyWindowMode::kaiser;const bool custom=c.filter=="custom";cusignal::ResamplePolyCpuResult cr;cusignal::ResamplePolyDeviceResult gr;
 auto cpu=measure(c.warmup,c.measured,[&]{cr=cusignal::resample_poly_typed_cpu(x,c.up,c.down,opt,custom?&h:nullptr);});auto gpu=measure(c.warmup,c.measured,[&]{auto dx=cusignal::DeviceArray<T>::from_host(x);std::optional<cusignal::DeviceArray<T>>dh;if(custom)dh.emplace(cusignal::DeviceArray<T>::from_host(h));cusignal::resample_poly_device(dx,c.up,c.down,gr,opt,dh?&*dh:nullptr);auto sink=gpu_values(gr);});
 std::vector<Phase>ct{phase("before",0,false),phase("allocate",1,false),phase("h2d",2,false)};auto tc=cusignal::resample_poly_typed_cpu(x,c.up,c.down,opt,custom?&h:nullptr);ct.push_back(phase("execute_sync",3,false));ct.push_back(phase("d2h",4,false));tc={};ct.push_back(phase("release_sync",5,false));ct.push_back(phase("after",6,false));
 std::vector<Phase>gt;cusignal::cuda_utils::synchronize_stream();gt.push_back(phase("before",0,true));auto dx=cusignal::DeviceArray<T>::from_host(x);std::optional<cusignal::DeviceArray<T>>dh;if(custom)dh.emplace(cusignal::DeviceArray<T>::from_host(h));cusignal::ResamplePolyDeviceResult tg;gt.push_back(phase("allocate",1,true));gt.push_back(phase("h2d",2,true));cusignal::resample_poly_device(dx,c.up,c.down,tg,opt,dh?&*dh:nullptr);cusignal::cuda_utils::synchronize_stream();gt.push_back(phase("execute_sync",3,true));auto go=gpu_values(tg);gt.push_back(phase("d2h",4,true));tg={};dx={};dh.reset();cusignal::cuda_utils::synchronize_stream();gt.push_back(phase("release_sync",5,true));gt.push_back(phase("after",6,true));
 auto cv=cpu_values(cr),gv=gpu_values(gr);auto a=zkx::common::compare(cv,gv,1e-12);std::ostringstream manifest;manifest<<"x:"<<c.dtype<<":["<<x.size()<<"]:bytes="<<x.size()*sizeof(T)<<":sha256="<<digest(x);if(custom)manifest<<"|h:"<<c.dtype<<":[5]:bytes="<<h.size()*sizeof(T)<<":sha256="<<digest(h);std::string in=zkx::remaining_operator_case::sha256_hex(manifest.str()),od=dtype_name(cr.dtype);
 if(fs::exists(c.output))throw std::runtime_error("output exists");std::ofstream o(c.output);o<<"{\"schema_version\":1,\"operator_name\":\"resample_poly\",\"backend\":\"not_applicable\",\"requested_dtype\":\""<<c.dtype<<"\",\"compute_dtype\":\""<<(c.filter=="identity"?"identity_copy":"FP32")<<"\",\"fft_dtype\":\"not_applicable\",\"output_dtype\":\""<<od<<"\",\"filter_mode\":\""<<c.filter<<"\",\"axis\":"<<c.axis<<",\"up\":"<<c.up<<",\"down\":"<<c.down<<",\"typed_input_count\":"<<(custom?2:1)<<",\"typed_input_manifest\":\""<<manifest.str()<<"\",\"actual_input_digest\":\""<<in<<"\",\"cpu_output_digest\":\""<<digest(cv)<<"\",\"gpu_output_digest\":\""<<digest(gv)<<"\",\"output_shape\":["<<cr.shape[0]<<','<<cr.shape[1]<<"],\"mse\":"<<std::setprecision(17)<<a.mse<<",\"rmse\":"<<a.rmse<<",\"relative_l2\":"<<a.relative_l2<<",\"relative_linf\":"<<a.relative_linf<<",\"cpu_samples_ms\":";samples(o,cpu);o<<",\"gpu_samples_ms\":";samples(o,gpu);o<<",\"cpu_trace\":";phases(o,ct);o<<",\"gpu_trace\":";phases(o,gt);o<<"}\n";std::cout<<"REMAINING_OPERATOR_CASE_RESAMPLE_POLY_PROBE PASS dtype="<<c.dtype<<" filter="<<c.filter<<" backend=not_applicable\n";return 0;}
}
int main(int argc,char**argv){try{auto c=cli(argc,argv);if(c.dtype=="FP32")return run<float>(c);if(c.dtype=="FP16")return run<__half>(c);if(c.dtype=="INT32")return run<std::int32_t>(c);if(c.dtype=="INT16")return run<std::int16_t>(c);if(c.dtype=="INT8")return run<std::int8_t>(c);throw std::invalid_argument("dtype");}catch(const std::exception&e){std::cerr<<"REMAINING_OPERATOR_CASE_RESAMPLE_POLY_PROBE FAIL error="<<e.what()<<'\n';return 2;}}
