#!/usr/bin/env python3
import argparse,csv,hashlib,json,math,pathlib,re,subprocess,sys
sys.path.insert(0,str(pathlib.Path(__file__).resolve().parents[1]/"channelize_poly"));import run_operator as common
def args():
 p=argparse.ArgumentParser();p.add_argument("--binary",required=True);p.add_argument("--config",required=True);p.add_argument("--thresholds",required=True);p.add_argument("--results-root",required=True);p.add_argument("--scale",required=True);p.add_argument("--run-type",choices=("smoke","formal"),required=True);p.add_argument("--git-commit",required=True);p.add_argument("--git-dirty",choices=("true","false"),required=True);p.add_argument("--test-time-utc",required=True);p.add_argument("--random",required=True);return p.parse_args()
def load(p):raw=pathlib.Path(p).read_bytes();return json.loads(raw.decode()),hashlib.sha256(raw).hexdigest()
def ident(a,c,sha,s,run,case,dev,status,code):return dict(zip(common.IDENTITY,["1",run,a.run_type,a.test_time_utc,a.git_commit,a.git_dirty,c["scale_set_id"],sha,"operator","resample_poly","NA","NA","resample_poly",case,s["scale_id"],s["order_of_magnitude"],str(s["actual_elements"]),";".join(x["input_name"]+"=["+"x".join(map(str,x["shape"]))+"]" for x in s["inputs"]),s["inputs"][0]["dtype"],dev,"not_applicable","compatibility/end-to-end",status,code]))
def main():
 a=args();c,sha=load(a.config);ts,_=load(a.thresholds);ss=[s for o in c["operators"] if o["operator_name"]=="resample_poly" for s in o["scales"] if s["scale_id"]==a.scale]
 if len(ss)!=1 or not re.fullmatch(r"[0-9a-f]{40}",a.git_commit):raise ValueError("identity")
 s=ss[0];i=s["inputs"];p=s["parameters"];dtype=i[0]["dtype"];custom=p["filter_mode"]=="custom";identity=p["filter_mode"]=="identity"
 if len(i)!=(2 if custom else 1) or i[0]["input_name"]!="x" or custom and (i[1]["input_name"]!="h" or i[1]["dtype"]!=dtype) or any(math.prod(x["shape"])!=x["element_count"] for x in i) or s["actual_elements"]!=sum(x["element_count"] for x in i):raise ValueError("typed inputs")
 out=dtype if identity else ("FP64" if (not custom or dtype=="INT32") else "FP32");compute="identity_copy" if identity else "FP32";sem="actual_typed_array_inputs" if custom else "actual_typed_array_input"
 if (p["output_dtype"],p["compute_dtype"],p["dtype_semantics"],p["typed_input_names"],p["backend"],p["fft_dtype"])!=(out,compute,sem,"x|h" if custom else "x","not_applicable","not_applicable"):raise ValueError("compute contract")
 th=[x for x in ts["entries"] if x["target"]=="resample_poly" and x["dtype"]==dtype][0];warm,measured=(20,100) if a.run_type=="formal" else (1,1);run=f"{a.test_time_utc}_{a.git_commit[:12]}_remaining_operator_case_b04_{a.run_type}_{a.random}";d=pathlib.Path(a.results_root)/a.run_type/run
 if d.exists():raise RuntimeError("run exists")
 d.mkdir(parents=True);rawp=d/"resample_poly_probe_raw.json";log=d/"operator_resample_poly_full.log";cmd=[a.binary,"--dtype",dtype,"--rows",str(i[0]["shape"][0]),"--cols",str(i[0]["shape"][1]),"--axis",str(p["axis"]),"--up",str(p["up"]),"--down",str(p["down"]),"--filter-mode",p["filter_mode"],"--seed",str(p["generator_seed"]),"--warmup",str(warm),"--measured",str(measured),"--output",str(rawp)];r=subprocess.run(cmd,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT);log.write_text("command="+" ".join(cmd)+"\n"+r.stdout)
 if r.returncode or not rawp.exists():raise RuntimeError(f"probe rc={r.returncode}")
 raw=json.loads(rawp.read_text());expected_shape=list(i[0]["shape"]);expected_shape[p["axis"]]=math.ceil(expected_shape[p["axis"]]*(p["up"]//math.gcd(p["up"],p["down"]))/(p["down"]//math.gcd(p["up"],p["down"])))
 if (raw["requested_dtype"],raw["output_dtype"],raw["filter_mode"],raw["typed_input_count"],raw["output_shape"])!=(dtype,out,p["filter_mode"],2 if custom else 1,expected_shape):raise RuntimeError("raw contract")
 ok=all(raw[k]<=th[k+"_max"] for k in ("mse","rmse","relative_l2","relative_linf"));vals=[common.resource_summary(raw[t],k) for t,k in (("cpu_trace","heap"),("cpu_trace","rss"),("gpu_trace","heap"),("gpu_trace","rss"),("gpu_trace","gpu"))];passed=ok and all(x is not None for x in vals);status="PASS" if passed else "FAIL";code="OK" if passed else "FAILED";case=f"resample_poly__{s['scale_id']}__{raw['actual_input_digest'][:16]}";cs,gs=common.stats(raw["cpu_samples_ms"]),common.stats(raw["gpu_samples_ms"]);speed=cs["mean_ms"]/gs["mean_ms"]
 def mr(dev,st,h,rss,gpu):
  q=ident(a,c,sha,s,run,case,dev,status,code);q.update({k:f"{v:.17g}" for k,v in st.items()});q.update({"warmup_runs":str(warm),"measured_runs":str(measured),"cpu_gpu_speedup":f"{speed:.17g}" if dev=="GPU" else "NA","accuracy_reference":"cpu_resample_poly_reference","mse":f"{raw['mse']:.17g}" if dev=="GPU" else "0","rmse":f"{raw['rmse']:.17g}" if dev=="GPU" else "0","relative_l2":f"{raw['relative_l2']:.17g}" if dev=="GPU" else "0","relative_linf":f"{raw['relative_linf']:.17g}" if dev=="GPU" else "0","exact_match":"NA","mismatch_count":"NA","semantic_check":th["semantic_rule"]+f":filter={p['filter_mode']};ratio={p['up']}/{p['down']};axis={p['axis']}","accuracy_status":"PASS" if ok else "FAIL"});
  for pre,val in (("cpu_heap",h),("rss",rss),("gpu",gpu)):
   for f in ("before","after","peak","delta"):q[f"{pre}_{f}_bytes"]=str(val[f]) if val else "NA"
  for k in common.SUMMARY:q.setdefault(k,"NA")
  return q
 common.write_csv(d/f"operator_main_results_resample_poly_not_applicable_{run}.csv",common.IDENTITY+common.SUMMARY,[mr("CPU",cs,vals[0],vals[1],None),mr("GPU",gs,vals[2],vals[3],vals[4])]);tc=common.IDENTITY+["warmup_runs","measured_runs","sample_index","latency_ms","synchronized","input_digest","output_digest"];tr=[]
 for dev,ssamp,od in (("CPU",raw["cpu_samples_ms"],raw["cpu_output_digest"]),("GPU",raw["gpu_samples_ms"],raw["gpu_output_digest"])):
  for n,v in enumerate(ssamp):q=ident(a,c,sha,s,run,case,dev,status,code);q.update({"warmup_runs":str(warm),"measured_runs":str(measured),"sample_index":str(n),"latency_ms":f"{v:.17g}","synchronized":"true","input_digest":raw["actual_input_digest"],"output_digest":od});tr.append(q)
 common.write_csv(d/f"operator_timing_samples_resample_poly_not_applicable_{run}.csv",tc,tr);mc=common.IDENTITY+["sample_index","trace_phase","phase_index","cpu_live_heap_bytes","rss_bytes","gpu_used_bytes"];mem=[]
 for dev,trace in (("CPU",raw["cpu_trace"]),("GPU",raw["gpu_trace"])):
  for x in trace:q=ident(a,c,sha,s,run,case,dev,status,code);q.update({"sample_index":"0","trace_phase":x["phase"],"phase_index":str(x["phase_index"]),"cpu_live_heap_bytes":str(x["heap"]["bytes"]) if x["heap"]["available"] else "NA","rss_bytes":str(x["rss"]["bytes"]) if x["rss"]["available"] else "NA","gpu_used_bytes":str(x["gpu"]["bytes"]) if x["gpu"]["available"] else "NA"});mem.append(q)
 common.write_csv(d/"operator_filtering_resample_poly_memory_trace_not_applicable.csv",mc,mem);common.write_csv(d/f"operator_dtype_evidence_resample_poly_not_applicable_{run}.csv",["run_id","case_id","operator_name","requested_dtype","dtype_semantics","typed_input_count","typed_input_manifest","actual_input_digest","compute_dtype","fft_dtype","output_dtype","status","error_code"],[{"run_id":run,"case_id":case,"operator_name":"resample_poly","requested_dtype":dtype,"dtype_semantics":sem,"typed_input_count":str(2 if custom else 1),"typed_input_manifest":raw["typed_input_manifest"],"actual_input_digest":raw["actual_input_digest"],"compute_dtype":compute,"fft_dtype":"not_applicable","output_dtype":out,"status":status,"error_code":code}]);report={"schema_version":1,"run_id":run,"case_id":case,"operator_name":"resample_poly","scale_id":s["scale_id"],"requested_dtype":dtype,"dtype_semantics":sem,"typed_input_names":"x|h" if custom else "x","compute_dtype":compute,"fft_dtype":"not_applicable","output_dtype":out,"backend":"not_applicable","filter_mode":p["filter_mode"],"axis":p["axis"],"up":p["up"],"down":p["down"],"typed_input_count":2 if custom else 1,"warmup_runs":warm,"measured_runs":measured,"actual_input_digest":raw["actual_input_digest"],"mse":raw["mse"],"rmse":raw["rmse"],"relative_l2":raw["relative_l2"],"relative_linf":raw["relative_linf"],"status":status,"error_code":code};(d/"operator_resample_poly_report.json").write_text(json.dumps(report,indent=2)+"\n");(d/"operator_resample_poly_summary.txt").write_text("\n".join(f"{k}={v}" for k,v in report.items())+"\n");log.write_text(log.read_text()+json.dumps(report,sort_keys=True)+"\n");print(f"REMAINING_OPERATOR_CASE_RESAMPLE_POLY_CASE {status} scale={s['scale_id']} dtype={dtype} backend=not_applicable measured={measured} results={d}");return 0 if passed else 3
if __name__=="__main__":
 try:sys.exit(main())
 except Exception as e:print(f"REMAINING_OPERATOR_CASE_RESAMPLE_POLY_DRIVER FAIL error={e}",file=sys.stderr);sys.exit(2)
