#include "accuracy.h"
#include <cusignal/runtime/cuda_utils.h>
#include "memory.h"
#include "sha256.h"
#include <cusignal/operators/spectral_analysis/spectral_analysis_typed.h>
#include <cuda_fp16.h>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>
namespace{namespace fs=std::filesystem;struct C{std::string dt;int bins,frames,nperseg,noverlap,nfft;float rate;bool onesided,boundary;uint64_t seed;size_t warm,measured;fs::path out;};struct P{std::string n;int i;zkx::common::ResourceSample h,r,g;};
C cli(int n,char**a){std::map<std::string,std::string>v;for(int i=1;i<n;i+=2)v.emplace(std::string(a[i]).substr(2),a[i+1]);auto g=[&](const char*k)->const std::string&{auto x=v.find(k);if(x==v.end())throw std::invalid_argument(k);return x->second;};return{g("dtype"),std::stoi(g("bins")),std::stoi(g("frames")),std::stoi(g("nperseg")),std::stoi(g("noverlap")),std::stoi(g("nfft")),std::stof(g("fs")),g("onesided")=="true",g("boundary")=="true",std::stoull(g("seed")),std::stoull(g("warmup")),std::stoull(g("measured")),g("output")};}
zkx::common::ResourceSample gs(){return zkx::common::sample_gpu_used([]{auto i=cusignal::cuda_utils::current_memory_info();return(int64_t)(i.total_bytes-i.free_bytes);},"cudaMemGetInfo.total_minus_free");}P ph(const char*n,int i,bool g){return{n,i,zkx::common::sample_cpu_heap(),zkx::common::sample_cpu_rss(),g?gs():zkx::common::ResourceSample{false,0,"NA","CPU"}};}template<class T>T cv(float x){return(T)x;}template<>__half cv<__half>(float x){return __float2half_rn(x);}template<class T>std::vector<cusignal::TypedComplex<T>>input(size_t n,uint64_t s){std::vector<cusignal::TypedComplex<T>>v;v.reserve(n);for(size_t i=0;i<n;i++){int a=(int)((i*17+s)%11)-5,b=(int)((i*7+s/3)%9)-4;float r=std::is_integral_v<T>?float(a):a*.25f+(i%13)*.03125f,im=std::is_integral_v<T>?float(b):b*.125f-(i%7)*.015625f;v.push_back({cv<T>(r),cv<T>(im)});}return v;}template<class T>std::string dg(const std::vector<T>&v){return zkx::remaining_operator_case::sha256_hex(std::string((char*)v.data(),v.size()*sizeof(T)));}template<class F>std::vector<double>meas(size_t w,size_t n,F f){for(size_t i=0;i<w;i++)f();std::vector<double>v;for(size_t i=0;i<n;i++){auto a=std::chrono::steady_clock::now();f();auto b=std::chrono::steady_clock::now();v.push_back(std::chrono::duration<double,std::milli>(b-a).count());}return v;}void ss(std::ostream&o,const std::vector<double>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<std::setprecision(17)<<v[i];}o<<']';}void rs(std::ostream&o,const zkx::common::ResourceSample&s){o<<"{\"available\":"<<(s.available?"true":"false")<<",\"bytes\":"<<(s.available?std::to_string(s.bytes):"null")<<'}';}void ps(std::ostream&o,const std::vector<P>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<"{\"phase\":\""<<v[i].n<<"\",\"phase_index\":"<<v[i].i<<",\"heap\":";rs(o,v[i].h);o<<",\"rss\":";rs(o,v[i].r);o<<",\"gpu\":";rs(o,v[i].g);o<<'}';}o<<']';}
std::vector<double>flat(const cusignal::IstftCpuResult&r){std::vector<double>v=r.times;if(r.is_fp64)v.insert(v.end(),r.fp64.begin(),r.fp64.end());else v.insert(v.end(),r.fp32.begin(),r.fp32.end());return v;}std::vector<double>flat(const cusignal::IstftDeviceResult&r){std::vector<double>v=r.times.to_host();if(r.is_fp64){auto x=r.fp64.to_host();v.insert(v.end(),x.begin(),x.end());}else{auto x=r.fp32.to_host();v.insert(v.end(),x.begin(),x.end());}return v;}
template<class T>int run(const C&c){auto z=input<T>((size_t)c.bins*c.frames,c.seed);cusignal::IstftDeviceParams p;p.fs=c.rate;p.window=cusignal::WindowParams("hann");p.nperseg=c.nperseg;p.noverlap=c.noverlap;p.nfft=c.nfft;p.input_onesided=c.onesided;p.boundary=c.boundary;cusignal::IstftCpuResult cr;cusignal::IstftDeviceResult gr;auto ct=meas(c.warm,c.measured,[&]{cr=cusignal::istft_typed_cpu(z,c.bins,c.frames,p);});auto gt=meas(c.warm,c.measured,[&]{auto dz=cusignal::DeviceArray<cusignal::TypedComplex<T>>::from_host(z);gr=cusignal::istft_device(dz,c.bins,c.frames,p);flat(gr);});
std::vector<P>cp;cp.push_back(ph("before",0,0));auto tz=z;cp.push_back(ph("allocate",1,0));cp.push_back(ph("h2d",2,0));auto tc=cusignal::istft_typed_cpu(tz,c.bins,c.frames,p);cp.push_back(ph("execute_sync",3,0));auto tch=flat(tc);cp.push_back(ph("d2h",4,0));tz.clear();tc={};tch.clear();cp.push_back(ph("release_sync",5,0));cp.push_back(ph("after",6,0));std::vector<P>gp;cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("before",0,1));cusignal::IstftDeviceResult tg;gp.push_back(ph("allocate",1,1));auto dz=cusignal::DeviceArray<cusignal::TypedComplex<T>>::from_host(z);gp.push_back(ph("h2d",2,1));tg=cusignal::istft_device(dz,c.bins,c.frames,p);cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("execute_sync",3,1));auto tgh=flat(tg);gp.push_back(ph("d2h",4,1));tg={};dz={};tgh.clear();cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("release_sync",5,1));gp.push_back(ph("after",6,1));
auto cvv=flat(cr),gv=flat(gr);auto ac=zkx::common::compare(cvv,gv,1e-12);if(!std::isfinite(ac.mse)||!std::isfinite(ac.rmse)||!std::isfinite(ac.relative_l2)||!std::isfinite(ac.relative_linf))throw std::runtime_error("nonfinite accuracy metric");std::string man="z:Complex"+c.dt+":frequency_major:["+std::to_string(c.bins)+","+std::to_string(c.frames)+"]:components="+c.dt+":bytes="+std::to_string(z.size()*sizeof(z[0]))+":sha256="+dg(z),id=zkx::remaining_operator_case::sha256_hex(man),od=std::is_same_v<T,int32_t>?"FP64":"FP32";if(fs::exists(c.out))throw std::runtime_error("exists");std::ofstream o(c.out);o<<"{\"requested_dtype\":\""<<c.dt<<"\",\"output_dtype\":\""<<od<<"\",\"backend\":\""<<ZKX_SELECTED_FFT_BACKEND_NAME<<"\",\"frequency_count\":"<<c.bins<<",\"time_count\":"<<c.frames<<",\"nperseg\":"<<c.nperseg<<",\"noverlap\":"<<c.noverlap<<",\"nfft\":"<<c.nfft<<",\"input_onesided\":"<<(c.onesided?"true":"false")<<",\"boundary\":"<<(c.boundary?"true":"false")<<",\"output_length\":"<<cr.times.size()<<",\"typed_input_manifest\":\""<<man<<"\",\"actual_input_digest\":\""<<id<<"\",\"cpu_output_digest\":\""<<dg(cvv)<<"\",\"gpu_output_digest\":\""<<dg(gv)<<"\",\"mse\":"<<ac.mse<<",\"rmse\":"<<ac.rmse<<",\"relative_l2\":"<<ac.relative_l2<<",\"relative_linf\":"<<ac.relative_linf<<",\"cpu_samples_ms\":";ss(o,ct);o<<",\"gpu_samples_ms\":";ss(o,gt);o<<",\"cpu_trace\":";ps(o,cp);o<<",\"gpu_trace\":";ps(o,gp);o<<"}\n";return 0;}}
int main(int n,char**a){try{auto c=cli(n,a);if(c.dt=="FP32")return run<float>(c);if(c.dt=="FP16")return run<__half>(c);if(c.dt=="INT32")return run<int32_t>(c);if(c.dt=="INT16")return run<int16_t>(c);if(c.dt=="INT8")return run<int8_t>(c);return 2;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}}
