#include "accuracy.h"
#include <cusignal/runtime/cuda_utils.h>
#include "memory.h"
#include "sha256.h"
#include <cusignal/operators/waveforms/waveforms_typed.h>
#include <cuda_fp16.h>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <vector>
namespace{namespace fs=std::filesystem;struct C{std::string dt,mode;int n,idx;size_t warm,measured;fs::path out;};struct P{std::string n;int i;zkx::common::ResourceSample h,r,g;};C cli(int n,char**a){std::map<std::string,std::string>v;for(int i=1;i<n;i+=2)v.emplace(std::string(a[i]).substr(2),a[i+1]);auto g=[&](const char*k)->const std::string&{auto x=v.find(k);if(x==v.end())throw std::invalid_argument(k);return x->second;};return{g("dtype"),g("idx-mode"),std::stoi(g("shape")),std::stoi(g("idx")),std::stoull(g("warmup")),std::stoull(g("measured")),g("output")};}zkx::common::ResourceSample gs(){return zkx::common::sample_gpu_used([]{auto i=cusignal::cuda_utils::current_memory_info();return(int64_t)(i.total_bytes-i.free_bytes);},"cudaMemGetInfo.total_minus_free");}P ph(const char*n,int i,bool g){return{n,i,zkx::common::sample_cpu_heap(),zkx::common::sample_cpu_rss(),g?gs():zkx::common::ResourceSample{false,0,"NA","CPU"}};}std::string dg(const std::vector<double>&v){return zkx::remaining_operator_case::sha256_hex(std::string((const char*)v.data(),v.size()*sizeof(double)));}template<class F>std::vector<double>meas(size_t w,size_t n,F f){for(size_t i=0;i<w;i++)f();std::vector<double>v;for(size_t i=0;i<n;i++){auto a=std::chrono::steady_clock::now();f();auto b=std::chrono::steady_clock::now();v.push_back(std::chrono::duration<double,std::milli>(b-a).count());}return v;}void ss(std::ostream&o,const std::vector<double>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<std::setprecision(17)<<v[i];}o<<']';}void rs(std::ostream&o,const zkx::common::ResourceSample&s){o<<"{\"available\":"<<(s.available?"true":"false")<<",\"bytes\":"<<(s.available?std::to_string(s.bytes):"null")<<'}';}void ps(std::ostream&o,const std::vector<P>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<"{\"phase\":\""<<v[i].n<<"\",\"phase_index\":"<<v[i].i<<",\"heap\":";rs(o,v[i].h);o<<",\"rss\":";rs(o,v[i].r);o<<",\"gpu\":";rs(o,v[i].g);o<<'}';}o<<']';}
template<class T>int run(const C&c){std::vector<double>cr,gr;auto cpu=[&]{cr=cusignal::unit_impulse_typed_cpu<T>(c.n,c.idx);};auto gpu=[&]{cusignal::DeviceArray<double>o(c.n);cusignal::unit_impulse_device<T>(o,c.idx);gr=o.to_host();};auto ct=meas(c.warm,c.measured,cpu),gt=meas(c.warm,c.measured,gpu);std::vector<P>cp;cp.push_back(ph("before",0,0));std::vector<double>co;cp.push_back(ph("allocate",1,0));cp.push_back(ph("h2d",2,0));co=cusignal::unit_impulse_typed_cpu<T>(c.n,c.idx);cp.push_back(ph("execute_sync",3,0));auto ch=co;cp.push_back(ph("d2h",4,0));co.clear();ch.clear();cp.push_back(ph("release_sync",5,0));cp.push_back(ph("after",6,0));std::vector<P>gp;cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("before",0,1));cusignal::DeviceArray<double>go(c.n);gp.push_back(ph("allocate",1,1));gp.push_back(ph("h2d",2,1));cusignal::unit_impulse_device<T>(go,c.idx);cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("execute_sync",3,1));auto gh=go.to_host();gp.push_back(ph("d2h",4,1));go={};gh.clear();cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("release_sync",5,1));gp.push_back(ph("after",6,1));auto ac=zkx::common::compare(cr,gr,1e-12);std::string man="request_variant:"+c.dt+":dtype_argument_ignored:shape="+std::to_string(c.n)+":idx="+std::to_string(c.idx)+":mode="+c.mode,id=zkx::remaining_operator_case::sha256_hex(man);if(fs::exists(c.out))throw std::runtime_error("exists");std::ofstream o(c.out);o<<"{\"requested_dtype\":\""<<c.dt<<"\",\"output_dtype\":\"FP64\",\"backend\":\"not_applicable\",\"shape\":"<<c.n<<",\"idx\":"<<c.idx<<",\"idx_mode\":\""<<c.mode<<"\",\"output_count\":"<<cr.size()<<",\"request_variant_manifest\":\""<<man<<"\",\"actual_input_digest\":\""<<id<<"\",\"cpu_output_digest\":\""<<dg(cr)<<"\",\"gpu_output_digest\":\""<<dg(gr)<<"\",\"mse\":"<<ac.mse<<",\"rmse\":"<<ac.rmse<<",\"relative_l2\":"<<ac.relative_l2<<",\"relative_linf\":"<<ac.relative_linf<<",\"cpu_samples_ms\":";ss(o,ct);o<<",\"gpu_samples_ms\":";ss(o,gt);o<<",\"cpu_trace\":";ps(o,cp);o<<",\"gpu_trace\":";ps(o,gp);o<<"}\n";return 0;}int main_t(const C&c){if(c.dt=="FP32")return run<float>(c);if(c.dt=="FP16")return run<__half>(c);if(c.dt=="INT32")return run<int32_t>(c);if(c.dt=="INT16")return run<int16_t>(c);if(c.dt=="INT8")return run<int8_t>(c);return 2;}}
int main(int n,char**a){try{return main_t(cli(n,a));}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}}
