#!/usr/bin/env python3
import argparse,hashlib,json,pathlib,subprocess,sys
sys.path.insert(0,str(pathlib.Path(__file__).resolve().parents[2]/"filtering"/"channelize_poly"));import run_operator as common
def main():
 p=argparse.ArgumentParser();[p.add_argument("--"+x,required=True)for x in("binary","config","thresholds","results-root","scale","run-type","git-commit","git-dirty","test-time-utc","random")];a=p.parse_args();cb=pathlib.Path(a.config).read_bytes();c=json.loads(cb);h=hashlib.sha256(cb).hexdigest();s=[z for z in c["operators"][0]["scales"]if z["scale_id"]==a.scale][0];q=s["parameters"];dt=q["request_variant"];th=[z for z in json.loads(pathlib.Path(a.thresholds).read_text())["entries"]if z["dtype"]==dt][0];w,n=(20,100)if a.run_type=="formal"else(1,1);run=f"{a.test_time_utc}_{a.git_commit[:12]}_remaining_operator_case_b08_{a.run_type}_{a.random}";d=pathlib.Path(a.results_root)/a.run_type/run
 if d.exists():raise RuntimeError("exists")
 d.mkdir(parents=True);rawp=d/"unit_impulse_probe_raw.json";cmd=[a.binary,"--dtype",dt,"--shape",str(q["shape"]),"--idx",str(q["idx"]),"--idx-mode",q["idx_mode"],"--warmup",str(w),"--measured",str(n),"--output",str(rawp)];z=subprocess.run(cmd,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT);log=d/"operator_unit_impulse_full.log";log.write_text("command="+" ".join(cmd)+"\n"+z.stdout)
 if z.returncode:raise RuntimeError("probe")
 r=json.loads(rawp.read_text());metrics=("mse","rmse","relative_l2","relative_linf");ok=all(r[x]<=th[x+"_max"]for x in metrics)and r["shape"]==q["shape"]and r["output_count"]==q["shape"]and r["idx_mode"]==q["idx_mode"];rs=[common.resource_summary(r[x],y)for x,y in(("cpu_trace","heap"),("cpu_trace","rss"),("gpu_trace","heap"),("gpu_trace","rss"),("gpu_trace","gpu"))];st="PASS"if ok and all(x is not None for x in rs)else"FAIL";code="OK"if st=="PASS"else"FAILED";case=f"unit_impulse__{s['scale_id']}__{r['actual_input_digest'][:16]}"
 def ident(dev):return dict(zip(common.IDENTITY,["1",run,a.run_type,a.test_time_utc,a.git_commit,a.git_dirty,c["scale_set_id"],h,"operator","unit_impulse","NA","NA","unit_impulse",case,s["scale_id"],s["order_of_magnitude"],str(q["shape"]),f"shape={q['shape']},idx={q['idx']}",dt,dev,"not_applicable","compatibility/end-to-end",st,code]))
 cs,gs=common.stats(r["cpu_samples_ms"]),common.stats(r["gpu_samples_ms"]);rows=[]
 for dev,ss in(("CPU",cs),("GPU",gs)):
  x=ident(dev);x.update({k:str(v)for k,v in ss.items()});x.update({"warmup_runs":str(w),"measured_runs":str(n),"cpu_gpu_speedup":str(cs["mean_ms"]/gs["mean_ms"])if dev=="GPU"else"NA","accuracy_reference":"cpu_unit_impulse_fp64","mse":str(r["mse"]if dev=="GPU"else 0),"rmse":str(r["rmse"]if dev=="GPU"else 0),"relative_l2":str(r["relative_l2"]if dev=="GPU"else 0),"relative_linf":str(r["relative_linf"]if dev=="GPU"else 0),"semantic_check":f"shape={q['shape']};idx_mode={q['idx_mode']};dtype_argument_ignored=true","accuracy_status":"PASS"if ok else"FAIL"});[x.setdefault(k,"NA")for k in common.SUMMARY];rows.append(x)
 common.write_csv(d/f"operator_main_results_unit_impulse_not_applicable_{run}.csv",common.IDENTITY+common.SUMMARY,rows);tc=common.IDENTITY+["warmup_runs","measured_runs","sample_index","latency_ms","synchronized","input_digest","output_digest"];tr=[]
 for dev,arr,od in(("CPU",r["cpu_samples_ms"],r["cpu_output_digest"]),("GPU",r["gpu_samples_ms"],r["gpu_output_digest"])):
  for i,v in enumerate(arr):x=ident(dev);x.update({"warmup_runs":str(w),"measured_runs":str(n),"sample_index":str(i),"latency_ms":str(v),"synchronized":"true","input_digest":r["actual_input_digest"],"output_digest":od});tr.append(x)
 common.write_csv(d/f"operator_timing_samples_unit_impulse_not_applicable_{run}.csv",tc,tr);mc=common.IDENTITY+["sample_index","trace_phase","phase_index","cpu_live_heap_bytes","rss_bytes","gpu_used_bytes"];mr=[]
 for dev,trace in(("CPU",r["cpu_trace"]),("GPU",r["gpu_trace"])):
  for y in trace:x=ident(dev);x.update({"sample_index":"0","trace_phase":y["phase"],"phase_index":str(y["phase_index"]),"cpu_live_heap_bytes":str(y["heap"]["bytes"])if y["heap"]["available"]else"NA","rss_bytes":str(y["rss"]["bytes"])if y["rss"]["available"]else"NA","gpu_used_bytes":str(y["gpu"]["bytes"])if y["gpu"]["available"]else"NA"});mr.append(x)
 common.write_csv(d/"operator_waveforms_unit_impulse_memory_trace_not_applicable.csv",mc,mr);ev={"run_id":run,"case_id":case,"operator_name":"unit_impulse","requested_dtype":dt,"dtype_semantics":"request_variant_no_typed_business_input_dtype_argument_ignored_fp64_output","typed_input_count":"0","typed_input_manifest":r["request_variant_manifest"],"actual_input_digest":r["actual_input_digest"],"compute_dtype":"bit_pattern_write","fft_dtype":"not_applicable","output_dtype":"FP64","status":st,"error_code":code};common.write_csv(d/f"operator_dtype_evidence_unit_impulse_not_applicable_{run}.csv",list(ev),[ev]);rep={"run_id":run,"case_id":case,"operator_name":"unit_impulse","scale_id":s["scale_id"],"requested_dtype":dt,"output_dtype":"FP64","backend":"not_applicable","shape":q["shape"],"idx":q["idx"],"idx_mode":q["idx_mode"],"output_count":r["output_count"],"warmup_runs":w,"measured_runs":n,**{x:r[x]for x in metrics},"status":st,"error_code":code};(d/"operator_unit_impulse_report.json").write_text(json.dumps(rep,indent=2)+"\n");(d/"operator_unit_impulse_summary.txt").write_text("\n".join(f"{k}={v}"for k,v in rep.items())+"\n");log.write_text(log.read_text()+json.dumps(rep)+"\n");print(f"REMAINING_OPERATOR_CASE_UNIT_IMPULSE_CASE {st} scale={s['scale_id']} dtype_request={dt} backend=not_applicable measured={n} results={d}");return 0 if st=="PASS"else 3
if __name__=="__main__":
 try:sys.exit(main())
 except Exception as e:print(e,file=sys.stderr);sys.exit(2)
