#include "accuracy.h"
#include <cusignal/runtime/cuda_utils.h>
#include <cusignal/operators/filtering/filtering_typed.h>
#include "memory.h"
#include "sha256.h"
#include <cuda_fp16.h>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>
namespace{namespace fs=std::filesystem;struct C{std::string dt;int rank,rows,cols,sections,axis;bool zi;std::uint64_t seed;std::size_t warm,measured;fs::path out;};struct P{std::string n;int i;zkx::common::ResourceSample h,r,g;};
C cli(int n,char**a){std::map<std::string,std::string>v;for(int i=1;i<n;i+=2)v.emplace(std::string(a[i]).substr(2),a[i+1]);auto g=[&](const char*k)->const std::string&{auto x=v.find(k);if(x==v.end())throw std::invalid_argument(k);return x->second;};return{g("dtype"),std::stoi(g("rank")),std::stoi(g("rows")),std::stoi(g("cols")),std::stoi(g("sections")),std::stoi(g("axis")),g("zi")=="true",std::stoull(g("seed")),std::stoull(g("warmup")),std::stoull(g("measured")),g("output")};}
zkx::common::ResourceSample gs(){return zkx::common::sample_gpu_used([]{auto i=cusignal::cuda_utils::current_memory_info();return(std::int64_t)(i.total_bytes-i.free_bytes);},"cudaMemGetInfo.total_minus_free");}P ph(const char*n,int i,bool g){return{n,i,zkx::common::sample_cpu_heap(),zkx::common::sample_cpu_rss(),g?gs():zkx::common::ResourceSample{false,0,"NA","CPU"}};}template<class T>T cv(float x){return(T)x;}template<>__half cv<__half>(float x){return __float2half_rn(x);}template<class T>std::vector<T> input(size_t n,uint64_t s){std::vector<T>v;for(size_t i=0;i<n;i++){int z=(int)((i*13+s)%9)-4;v.push_back(cv<T>(std::is_integral_v<T>?float(z):z*.25f));}return v;}template<class T>std::vector<T>sos(int n){std::vector<T>v(n*6,cv<T>(0));for(int i=0;i<n;i++){v[i*6]=cv<T>(1);v[i*6+1]=cv<T>(1);v[i*6+3]=cv<T>(1);}return v;}template<class T>std::string dg(const std::vector<T>&v){return zkx::remaining_operator_case::sha256_hex(std::string((char*)v.data(),v.size()*sizeof(T)));}template<class F>std::vector<double>meas(size_t w,size_t n,F f){for(size_t i=0;i<w;i++)f();std::vector<double>v;for(size_t i=0;i<n;i++){auto a=std::chrono::steady_clock::now();f();auto b=std::chrono::steady_clock::now();v.push_back(std::chrono::duration<double,std::milli>(b-a).count());}return v;}void ss(std::ostream&o,const std::vector<double>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<std::setprecision(17)<<v[i];}o<<']';}void rs(std::ostream&o,const zkx::common::ResourceSample&s){o<<"{\"available\":"<<(s.available?"true":"false")<<",\"bytes\":"<<(s.available?std::to_string(s.bytes):"null")<<'}';}void ps(std::ostream&o,const std::vector<P>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<"{\"phase\":\""<<v[i].n<<"\",\"phase_index\":"<<v[i].i<<",\"heap\":";rs(o,v[i].h);o<<",\"rss\":";rs(o,v[i].r);o<<",\"gpu\":";rs(o,v[i].g);o<<'}';}o<<']';}
template<class T>int run(const C&c){
 size_t n=(size_t)c.rows*(c.rank==2?c.cols:1);auto x=input<T>(n,c.seed),co=sos<T>(c.sections);std::vector<T>zi;if(c.zi)zi.assign((size_t)c.sections*2*(c.rank==2?(c.axis==0?c.cols:c.rows):1),cv<T>(1));cusignal::SosfiltOptions op;op.shape=c.rank==1?std::vector<int>{c.rows}:std::vector<int>{c.rows,c.cols};op.axis=c.axis;if(c.zi)op.zi_shape=c.rank==1?std::vector<int>{c.sections,2}:(c.axis==0?std::vector<int>{c.sections,2,c.cols}:std::vector<int>{c.sections,c.rows,2});
 cusignal::SosfiltCpuResult cr;cusignal::SosfiltDeviceResult gr;auto ct=meas(c.warm,c.measured,[&]{cr=cusignal::sosfilt_typed_cpu(co,c.sections,x,op,c.zi?&zi:nullptr);});auto gt=meas(c.warm,c.measured,[&]{auto ds=cusignal::DeviceArray<T>::from_host(co),dx=cusignal::DeviceArray<T>::from_host(x),dz=cusignal::DeviceArray<T>::from_host(zi);cusignal::sosfilt_device(ds,c.sections,dx,gr,op,c.zi?&dz:nullptr);gr.y.to_host();if(c.zi)gr.zf.to_host();});
 std::vector<P>cp;cp.push_back(ph("before",0,0));std::vector<T>tco=co,tx=x,tzi=zi;cp.push_back(ph("allocate",1,0));cp.push_back(ph("h2d",2,0));auto tcr=cusignal::sosfilt_typed_cpu(tco,c.sections,tx,op,c.zi?&tzi:nullptr);cp.push_back(ph("execute_sync",3,0));auto tcy=tcr.y;auto tcz=tcr.zf;cp.push_back(ph("d2h",4,0));tco.clear();tx.clear();tzi.clear();tcr={};tcy.clear();tcz.clear();cp.push_back(ph("release_sync",5,0));cp.push_back(ph("after",6,0));
 std::vector<P>gp;cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("before",0,1));cusignal::SosfiltDeviceResult tgr;gp.push_back(ph("allocate",1,1));auto ds=cusignal::DeviceArray<T>::from_host(co),dx=cusignal::DeviceArray<T>::from_host(x),dz=cusignal::DeviceArray<T>::from_host(zi);gp.push_back(ph("h2d",2,1));cusignal::sosfilt_device(ds,c.sections,dx,tgr,op,c.zi?&dz:nullptr);cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("execute_sync",3,1));auto ty=tgr.y.to_host();std::vector<float>tz;if(c.zi)tz=tgr.zf.to_host();gp.push_back(ph("d2h",4,1));tgr={};ds={};dx={};dz={};ty.clear();tz.clear();cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("release_sync",5,1));gp.push_back(ph("after",6,1));
 auto gy=gr.y.to_host();auto a=zkx::common::compare(std::vector<double>(cr.y.begin(),cr.y.end()),std::vector<double>(gy.begin(),gy.end()),1e-12);std::string man="sos:"+c.dt+":["+std::to_string(co.size())+"]:bytes="+std::to_string(co.size()*sizeof(T))+":sha256="+dg(co)+"|x:"+c.dt+":["+std::to_string(x.size())+"]:bytes="+std::to_string(x.size()*sizeof(T))+":sha256="+dg(x);if(c.zi)man+="|zi:"+c.dt+":["+std::to_string(zi.size())+"]:bytes="+std::to_string(zi.size()*sizeof(T))+":sha256="+dg(zi);std::string id=zkx::remaining_operator_case::sha256_hex(man);if(fs::exists(c.out))throw std::runtime_error("exists");std::ofstream o(c.out);o<<"{\"requested_dtype\":\""<<c.dt<<"\",\"output_dtype\":\"FP32\",\"sections\":"<<c.sections<<",\"axis\":"<<c.axis<<",\"rank\":"<<c.rank<<",\"has_zi\":"<<(c.zi?"true":"false")<<",\"has_zf\":"<<(gr.has_zf?"true":"false")<<",\"typed_input_manifest\":\""<<man<<"\",\"actual_input_digest\":\""<<id<<"\",\"cpu_output_digest\":\""<<dg(cr.y)<<"\",\"gpu_output_digest\":\""<<dg(gy)<<"\",\"mse\":"<<a.mse<<",\"rmse\":"<<a.rmse<<",\"relative_l2\":"<<a.relative_l2<<",\"relative_linf\":"<<a.relative_linf<<",\"cpu_samples_ms\":";ss(o,ct);o<<",\"gpu_samples_ms\":";ss(o,gt);o<<",\"cpu_trace\":";ps(o,cp);o<<",\"gpu_trace\":";ps(o,gp);o<<"}\n";return 0;}
}
int main(int n,char**a){try{auto c=cli(n,a);if(c.dt=="FP32")return run<float>(c);if(c.dt=="FP16")return run<__half>(c);if(c.dt=="INT32")return run<int32_t>(c);if(c.dt=="INT16")return run<int16_t>(c);if(c.dt=="INT8")return run<int8_t>(c);return 2;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}}
