#include "accuracy.h"
#include <cusignal/runtime/cuda_utils.h>
#include "memory.h"
#include "sha256.h"
#include <cusignal/operators/spectral_analysis/spectral_analysis_typed.h>
#include <cuda_fp16.h>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>
namespace{namespace fs=std::filesystem;struct C{std::string dt;int n,p;bool scalar;uint64_t seed;size_t warm,measured;fs::path out;};struct P{std::string n;int i;zkx::common::ResourceSample h,r,g;};
C cli(int n,char**a){std::map<std::string,std::string>v;for(int i=1;i<n;i+=2)v.emplace(std::string(a[i]).substr(2),a[i+1]);auto g=[&](const char*k)->const std::string&{auto x=v.find(k);if(x==v.end())throw std::invalid_argument(k);return x->second;};return{g("dtype"),std::stoi(g("events")),std::stoi(g("periods")),g("period-mode")=="scalar",std::stoull(g("seed")),std::stoull(g("warmup")),std::stoull(g("measured")),g("output")};}
zkx::common::ResourceSample gs(){return zkx::common::sample_gpu_used([]{auto i=cusignal::cuda_utils::current_memory_info();return(int64_t)(i.total_bytes-i.free_bytes);},"cudaMemGetInfo.total_minus_free");}P ph(const char*n,int i,bool g){return{n,i,zkx::common::sample_cpu_heap(),zkx::common::sample_cpu_rss(),g?gs():zkx::common::ResourceSample{false,0,"NA","CPU"}};}template<class T>T cv(float x){return(T)x;}template<>__half cv<__half>(float x){return __float2half_rn(x);}template<class T>std::vector<T>events(int n,uint64_t s){std::vector<T>v;for(int i=0;i<n;i++){float x=std::is_integral_v<T>?float((i*3+i/7+s%5)%101):i*.125f+(i%7)*.0078125f;v.push_back(cv<T>(x));}return v;}template<class T>std::vector<T>periods(int n){std::vector<T>v;for(int i=0;i<n;i++){float x=std::is_integral_v<T>?float(i+3):.5f+(i+1)*.25f;v.push_back(cv<T>(x));}return v;}template<class T>std::string dg(const std::vector<T>&v){return zkx::remaining_operator_case::sha256_hex(std::string((char*)v.data(),v.size()*sizeof(T)));}template<class F>std::vector<double>meas(size_t w,size_t n,F f){for(size_t i=0;i<w;i++)f();std::vector<double>v;for(size_t i=0;i<n;i++){auto a=std::chrono::steady_clock::now();f();auto b=std::chrono::steady_clock::now();v.push_back(std::chrono::duration<double,std::milli>(b-a).count());}return v;}void ss(std::ostream&o,const std::vector<double>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<std::setprecision(17)<<v[i];}o<<']';}void rs(std::ostream&o,const zkx::common::ResourceSample&s){o<<"{\"available\":"<<(s.available?"true":"false")<<",\"bytes\":"<<(s.available?std::to_string(s.bytes):"null")<<'}';}void ps(std::ostream&o,const std::vector<P>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<"{\"phase\":\""<<v[i].n<<"\",\"phase_index\":"<<v[i].i<<",\"heap\":";rs(o,v[i].h);o<<",\"rss\":";rs(o,v[i].r);o<<",\"gpu\":";rs(o,v[i].g);o<<'}';}o<<']';}
std::vector<double>flat(const cusignal::VectorStrengthCpuResult&r){std::vector<double>v=r.strength;v.insert(v.end(),r.phase.begin(),r.phase.end());return v;}std::vector<double>flat(const cusignal::VectorStrengthDeviceResult&r){std::vector<double>v=r.strength.to_host(),p=r.phase.to_host();v.insert(v.end(),p.begin(),p.end());return v;}
template<class T>int run(const C&c){auto e=events<T>(c.n,c.seed),p=periods<T>(c.p);cusignal::VectorStrengthCpuResult cr;cusignal::VectorStrengthDeviceResult gr;auto cpu=[&]{cr=c.scalar?cusignal::vectorstrength_typed_cpu(e,p[0]):cusignal::vectorstrength_typed_cpu(e,p);};auto gpu=[&]{auto de=cusignal::DeviceArray<T>::from_host(e);gr=c.scalar?cusignal::vectorstrength_device(de,p[0]):cusignal::vectorstrength_device(de,cusignal::DeviceArray<T>::from_host(p));flat(gr);};auto ct=meas(c.warm,c.measured,cpu),gt=meas(c.warm,c.measured,gpu);
std::vector<P>cp;cp.push_back(ph("before",0,0));auto te=e,tp=p;cp.push_back(ph("allocate",1,0));cp.push_back(ph("h2d",2,0));auto tc=c.scalar?cusignal::vectorstrength_typed_cpu(te,tp[0]):cusignal::vectorstrength_typed_cpu(te,tp);cp.push_back(ph("execute_sync",3,0));auto tch=flat(tc);cp.push_back(ph("d2h",4,0));te.clear();tp.clear();tc={};tch.clear();cp.push_back(ph("release_sync",5,0));cp.push_back(ph("after",6,0));std::vector<P>gp;cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("before",0,1));gp.push_back(ph("allocate",1,1));auto de=cusignal::DeviceArray<T>::from_host(e),dp=cusignal::DeviceArray<T>::from_host(p);gp.push_back(ph("h2d",2,1));auto tg=c.scalar?cusignal::vectorstrength_device(de,p[0]):cusignal::vectorstrength_device(de,dp);cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("execute_sync",3,1));auto tgh=flat(tg);gp.push_back(ph("d2h",4,1));tg={};de={};dp={};tgh.clear();cusignal::cuda_utils::synchronize_stream();gp.push_back(ph("release_sync",5,1));gp.push_back(ph("after",6,1));
auto cvv=flat(cr),gv=flat(gr);auto ac=zkx::common::compare(cvv,gv,1e-12);if(!std::isfinite(ac.mse)||!std::isfinite(ac.rmse)||!std::isfinite(ac.relative_l2)||!std::isfinite(ac.relative_linf))throw std::runtime_error("nonfinite accuracy metric");std::string second=c.scalar?"period:"+c.dt+":scalar:bytes="+std::to_string(sizeof(T))+":sha256="+dg(p):"periods:"+c.dt+":["+std::to_string(p.size())+"]:bytes="+std::to_string(p.size()*sizeof(T))+":sha256="+dg(p),man="events:"+c.dt+":["+std::to_string(e.size())+"]:bytes="+std::to_string(e.size()*sizeof(T))+":sha256="+dg(e)+"|"+second,id=zkx::remaining_operator_case::sha256_hex(man);if(fs::exists(c.out))throw std::runtime_error("exists");std::ofstream o(c.out);o<<"{\"requested_dtype\":\""<<c.dt<<"\",\"output_dtype\":\"FP64_pair\",\"backend\":\"not_applicable\",\"event_count\":"<<c.n<<",\"period_count\":"<<c.p<<",\"period_mode\":\""<<(c.scalar?"scalar":"array")<<"\",\"scientific_work\":"<<c.n*c.p<<",\"output_count\":"<<cr.strength.size()<<",\"scalar_period\":"<<(cr.scalar_period?"true":"false")<<",\"typed_input_manifest\":\""<<man<<"\",\"actual_input_digest\":\""<<id<<"\",\"cpu_output_digest\":\""<<dg(cvv)<<"\",\"gpu_output_digest\":\""<<dg(gv)<<"\",\"mse\":"<<ac.mse<<",\"rmse\":"<<ac.rmse<<",\"relative_l2\":"<<ac.relative_l2<<",\"relative_linf\":"<<ac.relative_linf<<",\"cpu_samples_ms\":";ss(o,ct);o<<",\"gpu_samples_ms\":";ss(o,gt);o<<",\"cpu_trace\":";ps(o,cp);o<<",\"gpu_trace\":";ps(o,gp);o<<"}\n";return 0;}}
int main(int n,char**a){try{auto c=cli(n,a);if(c.dt=="FP32")return run<float>(c);if(c.dt=="FP16")return run<__half>(c);if(c.dt=="INT32")return run<int32_t>(c);if(c.dt=="INT16")return run<int16_t>(c);if(c.dt=="INT8")return run<int8_t>(c);return 2;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}}
