#!/usr/bin/env python3
import argparse,csv,hashlib,json,pathlib,subprocess,sys
sys.path.insert(0,str(pathlib.Path(__file__).resolve().parents[2]/"cases"/"filtering"/"channelize_poly"));import run_operator as common
OPS={"hamming","firwin","firfilter"}
def table(title,columns,rows):
 values=[[str(row.get(key,"NA"))for key,_ in columns]for row in rows];widths=[max([len(label)]+[len(row[i])for row in values])for i,(_,label)in enumerate(columns)];line="+-"+"-+-".join("-"*width for width in widths)+"-+";body=[title,line,"| "+" | ".join(label.ljust(widths[i])for i,(_,label)in enumerate(columns))+" |",line];body.extend("| "+" | ".join(row[i].ljust(widths[i])for i in range(len(columns)))+" |"for row in values);body.append(line);return"\n".join(body)
def terminal_summary(main_path,paths):
 with main_path.open(encoding="utf-8",newline="")as h:main=list(csv.DictReader(h))
 pm=dict(paths)
 with pm["timing_csv"].open(encoding="utf-8",newline="")as h:timing=list(csv.DictReader(h))
 with pm["dtype_csv"].open(encoding="utf-8",newline="")as h:dtype_rows=list(csv.DictReader(h))
 blocks=[table("[stage07] identity and status",[("target","target"),("scale_id","scale_id"),("device","device"),("backend","backend"),("dtype","dtype"),("warmup_runs","warmup"),("measured_runs","measured"),("timing_scope","timing_scope"),("status","status"),("error_code","error_code")],main)]
 blocks.append(table("[stage07] timing detail",[("device","device"),("mean_ms","mean_ms"),("p50_ms","p50_ms"),("p95_ms","p95_ms"),("p99_ms","p99_ms"),("min_ms","min_ms"),("max_ms","max_ms"),("std_ms","std_ms"),("cv","cv"),("cpu_gpu_speedup","speedup")],main))
 gpu=next(row for row in main if row["device"]=="GPU");blocks.append(table("[stage07] accuracy detail",[("accuracy_reference","reference"),("mse","mse"),("rmse","rmse"),("relative_l2","relative_l2"),("relative_linf","relative_linf"),("exact_match","exact_match"),("mismatch_count","mismatch_count"),("semantic_check","semantic_check"),("accuracy_status","status")],[gpu]))
 resources=[]
 for row in main:
  for prefix,label in (("cpu_heap","cpu_heap"),("rss","rss"),("gpu","gpu_memory")):
   if row[f"{prefix}_before_bytes"]!="NA":resources.append({"device":row["device"],"metric":label,"before":row[f"{prefix}_before_bytes"],"after":row[f"{prefix}_after_bytes"],"peak":row[f"{prefix}_peak_bytes"],"delta":row[f"{prefix}_delta_bytes"]})
 blocks.append(table("[stage07] resource detail",[("device","device"),("metric","metric"),("before","before_bytes"),("after","after_bytes"),("peak","peak_bytes"),("delta","delta_bytes")],resources))
 content=json.loads(dtype_rows[0]["input_content_json"]);blocks.append(table("[stage07] input content",[("input_name","input_name"),("shape","shape"),("dtype","dtype"),("element_count","elements"),("generator","generator"),("preview_heacuda_api_tail2","values(head4/tail2)")],content));blocks.append(table("[stage07] case parameters",[("parameters","parameters")],[{"parameters":dtype_rows[0]["case_parameters_json"]}]))
 io=[]
 for dev in("CPU","GPU"):
  row=next(item for item in timing if item["device"]==dev);io.append({"device":dev,"input_digest":row["input_digest"],"output_digest":row["output_digest"]})
 blocks.append(table("[stage07] input and output identity",[("device","device"),("input_digest","input_digest"),("output_digest","output_digest")],io));blocks.append(table("[stage07] dtype evidence",[("requested_dtype","requested_dtype"),("config_input_dtype","config_input_dtype"),("output_dtype","output_dtype"),("typed_array_digest","typed_array_digest"),("actual_input_digest","actual_input_digest"),("operator_matrixpu_call_status","operator_matrixpu_call_status")],dtype_rows));blocks.append(table("[stage07] evidence files",[("kind","kind"),("path","path")],[{"kind":kind,"path":str(path)}for kind,path in paths]+[{"kind":"result_dir","path":str(main_path.parent)}]));return"\n\n".join(blocks)
def main():
 p=argparse.ArgumentParser();[p.add_argument("--"+x,required=True)for x in("binary","operator","config","thresholds","results-root","scale","run-type","git-commit","git-dirty","test-time-utc","random")];a=p.parse_args()
 if a.operator not in OPS:raise ValueError("operator outside Stage07 Batch04")
 cb=pathlib.Path(a.config).read_bytes();cfg=json.loads(cb);ch=hashlib.sha256(cb).hexdigest();op=next(x for x in cfg["operators"]if x["operator_name"]==a.operator);s=next(x for x in op["scales"]if x["scale_id"]==a.scale);q=s["parameters"];dtype=s["inputs"][0]["dtype"];th=next(x for x in json.loads(pathlib.Path(a.thresholds).read_text())["entries"]if x["target"]==a.operator and x["dtype"]==dtype);warm,measured=(20,100)if a.run_type=="formal"else(1,1);run=f"{a.test_time_utc}_{a.git_commit[:12]}_operator_case_b04_{a.run_type}_{a.random}";out=pathlib.Path(a.results_root)/a.run_type/run
 if out.exists():raise RuntimeError("result exists")
 out.mkdir(parents=True);rawp=out/f"{a.operator}_probe_raw.json"
 if a.operator=="hamming":cmd=[a.binary,"--dtype",dtype,"--n",str(q["n"]),"--taps","1","--cutoff","60","--fs","1000","--sym",str(q["sym"]).lower()]
 elif a.operator=="firwin":cmd=[a.binary,"--dtype",dtype,"--n",str(q["numtaps"]),"--taps","1","--batch",str(q.get("batch_count",1)),"--cutoff",str(q["cutoff_hz"]),"--fs",str(q["fs_hz"]),"--sym","true"]
 else:cmd=[a.binary,"--dtype",dtype,"--n",str(q["signal_count"]),"--taps",str(q["tap_count"]),"--cutoff","60","--fs","1000","--sym","true"]
 cmd += ["--warmup",str(warm),"--measured",str(measured),"--output",str(rawp)];z=subprocess.run(cmd,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT);log=out/f"operator_{a.operator}_full.log";log.write_text("command="+" ".join(cmd)+"\n"+z.stdout)
 if z.returncode:raise RuntimeError("probe failed: "+z.stdout)
 r=json.loads(rawp.read_text());metrics=("mse","rmse","relative_l2","relative_linf");accuracy_ok=all(r[x]<=th[x+"_max"]for x in metrics);expected=q["n"]if a.operator=="hamming"else q["numtaps"]*q.get("batch_count",1)if a.operator=="firwin"else q["signal_count"];semantic_ok=len(r["cpu_samples_ms"])==measured and r["output_dtype"]=="FP32" and r["output_count"]==expected;rs=[common.resource_summary(r[x],y)for x,y in(("cpu_trace","heap"),("cpu_trace","rss"),("gpu_trace","heap"),("gpu_trace","rss"),("gpu_trace","gpu"))];resource_ok=all(x is not None for x in rs);status="PASS"if accuracy_ok and semantic_ok and resource_ok else"FAIL";error="OK"if status=="PASS"else"RESOURCE_FAILED"if not resource_ok else"ACCURACY_FAILED";case=f"{a.operator}__{s['scale_id']}__{r['actual_input_digest'][:16]}";step="Step2"if a.operator!="firfilter"else"Step2;Step3"
 def ident(dev):return dict(zip(common.IDENTITY,["1",run,a.run_type,a.test_time_utc,a.git_commit,a.git_dirty,cfg["scale_set_id"],ch,"operator",a.operator,"Task2",step,a.operator,case,s["scale_id"],s["order_of_magnitude"],str(s["actual_elements"]),"|".join(i["input_name"]+"="+str(i["shape"])for i in s["inputs"]),dtype,dev,"not_applicable","compatibility/end-to-end",status,error]))
 cs,gs=common.stats(r["cpu_samples_ms"]),common.stats(r["gpu_samples_ms"]);rows=[]
 for dev,stats,heap,rss,gpu in(("CPU",cs,rs[0],rs[1],None),("GPU",gs,rs[2],rs[3],rs[4])):
  x=ident(dev);x.update({k:str(v)for k,v in stats.items()});x.update({"warmup_runs":str(warm),"measured_runs":str(measured),"cpu_gpu_speedup":str(cs["mean_ms"]/gs["mean_ms"])if dev=="GPU"else"NA","accuracy_reference":"typed_cpu_task_resident_reference","mse":str(r["mse"]if dev=="GPU"else 0),"rmse":str(r["rmse"]if dev=="GPU"else 0),"relative_l2":str(r["relative_l2"]if dev=="GPU"else 0),"relative_linf":str(r["relative_linf"]if dev=="GPU"else 0),"exact_match":"NA","mismatch_count":"NA","semantic_check":f"output_count={expected};output_dtype=FP32;operator_matrixpu_call=present","accuracy_status":"PASS"if accuracy_ok and semantic_ok else"FAIL"})
  for px,sm in(("cpu_heap",heap),("rss",rss),("gpu",gpu)):
   for fld in("before","after","peak","delta"):x[f"{px}_{fld}_bytes"]=str(sm[fld])if sm else"NA"
  [x.setdefault(k,"NA")for k in common.SUMMARY];rows.append(x)
 main_path=out/f"operator_main_results_{a.operator}_not_applicable_{run}.csv";common.write_csv(main_path,common.IDENTITY+common.SUMMARY,rows);tc=common.IDENTITY+["warmup_runs","measured_runs","sample_index","latency_ms","synchronized","input_digest","output_digest"];tr=[]
 for dev,samples,digest in(("CPU",r["cpu_samples_ms"],r["cpu_output_digest"]),("GPU",r["gpu_samples_ms"],r["gpu_output_digest"])):
  for i,v in enumerate(samples):x=ident(dev);x.update({"warmup_runs":str(warm),"measured_runs":str(measured),"sample_index":str(i),"latency_ms":str(v),"synchronized":"true","input_digest":r["actual_input_digest"],"output_digest":digest});tr.append(x)
 timing_path=out/f"operator_timing_samples_{a.operator}_not_applicable_{run}.csv";common.write_csv(timing_path,tc,tr);mc=common.IDENTITY+["sample_index","trace_phase","phase_index","cpu_live_heap_bytes","rss_bytes","gpu_used_bytes"];mr=[]
 for dev,trace in(("CPU",r["cpu_trace"]),("GPU",r["gpu_trace"])):
  for y in trace:x=ident(dev);x.update({"sample_index":"0","trace_phase":y["phase"],"phase_index":str(y["phase_index"]),"cpu_live_heap_bytes":str(y["heap"]["bytes"])if y["heap"]["available"]else"NA","rss_bytes":str(y["rss"]["bytes"])if y["rss"]["available"]else"NA","gpu_used_bytes":str(y["gpu"]["bytes"])if y["gpu"]["available"]else"NA"});mr.append(x)
 module={"hamming":"windows","firwin":"filter_design","firfilter":"filtering"}[a.operator];memory_path=out/f"operator_{module}_{a.operator}_memory_trace_not_applicable.csv";common.write_csv(memory_path,mc,mr)
 if a.operator=="hamming":content=[{"input_name":"request_spec","shape":"[1]","dtype":dtype,"element_count":"1","generator":"typed_hamming_request","preview_heacuda_api_tail2":r["preview0"]}]
 elif a.operator=="firwin":
  content=[{"input_name":"cutoff","shape":"[1]","dtype":dtype,"element_count":"1","generator":"configured_cutoff_scalar","preview_heacuda_api_tail2":r["preview0"]},{"input_name":"window","shape":f"[{q['numtaps']}]","dtype":"FP32","element_count":str(q["numtaps"]),"generator":"symmetric_hamming_explicit_window","preview_heacuda_api_tail2":r["preview1"]}]
  if "batch_count" in q:content.append({"input_name":"batch_count","shape":"[1]","dtype":"INT32","element_count":"1","generator":"configured_scientific_batch_count","preview_heacuda_api_tail2":f"i=0:{q['batch_count']}"})
 else:content=[{"input_name":"b","shape":f"[{q['tap_count']}]","dtype":dtype,"element_count":str(q["tap_count"]),"generator":"deterministic_nine_tap_smoother","preview_heacuda_api_tail2":r["preview0"]},{"input_name":"x","shape":f"[{q['signal_count']}]","dtype":dtype,"element_count":str(q["signal_count"]),"generator":"sinusoid_mixture_plus_modular_noise","preview_heacuda_api_tail2":r["preview1"]}]
 ev={"run_id":run,"case_id":case,"operator_name":a.operator,"requested_dtype":dtype,"config_input_dtype":dtype,"typed_input_manifest":r["typed_input_manifest"],"typed_array_digest":r["typed_array_digest"],"input_content_json":json.dumps(content,sort_keys=True,separators=(",",":")),"case_parameters_json":json.dumps(q,sort_keys=True,separators=(",",":")),"actual_input_digest":r["actual_input_digest"],"output_dtype":"FP32","backend":"not_applicable","operator_matrixpu_call_status":"proved_gpu_cpu","link_closure_note":"fft_thrust_linked_for_shared_translation_unit_not_executed","status":status,"error_code":error};dtype_path=out/f"operator_dtype_evidence_{a.operator}_not_applicable_{run}.csv";common.write_csv(dtype_path,list(ev),[ev]);rep={"run_id":run,"case_id":case,"operator_name":a.operator,"task_name":"Task2","step_name":step,"scale_id":s["scale_id"],"requested_dtype":dtype,"input_content":content,"case_parameters":q,"output_dtype":"FP32","backend":"not_applicable","warmup_runs":warm,"measured_runs":measured,**{m:r[m]for m in metrics},"actual_input_digest":r["actual_input_digest"],"typed_array_digest":r["typed_array_digest"],"status":status,"error_code":error};report_path=out/f"operator_{a.operator}_report.json";report_path.write_text(json.dumps(rep,indent=2)+"\n");summary_path=out/f"operator_{a.operator}_summary.txt";summary_path.write_text("\n".join(f"{k}={v}"for k,v in rep.items())+"\n");paths=[("main_csv",main_path),("timing_csv",timing_path),("memory_csv",memory_path),("dtype_csv",dtype_path),("report_json",report_path),("summary_txt",summary_path),("full_log",log)];terminal=terminal_summary(main_path,paths);log.write_text(log.read_text()+json.dumps(rep)+"\n"+terminal+"\n");print(terminal);print(f"OPERATOR_CASE_FILTER_CASE {status} operator={a.operator} scale={s['scale_id']} dtype={dtype} backend=not_applicable measured={measured} results={out}");return 0 if status=="PASS"else 3
if __name__=="__main__":
 try:sys.exit(main())
 except Exception as error:print(error,file=sys.stderr);sys.exit(2)
