#include "accuracy.h"
#include <cusignal/runtime/cuda_utils.h>
#include <cusignal/operators/filter_design/filter_design_typed.h>
#include <cusignal/operators/filtering/filtering_typed.h>
#include "memory.h"
#include "sha256.h"
#include <cusignal/operators/windows/windows_typed.h>
#include <cuda_fp16.h>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>
#ifndef ZKX_OPERATOR_CASE_FILTER_OPERATOR
#error "ZKX_OPERATOR_CASE_FILTER_OPERATOR required"
#endif
namespace{namespace fs=std::filesystem;constexpr const char*kOp=ZKX_OPERATOR_CASE_FILTER_OPERATOR;struct C{std::string dt;int n,taps,batch;double cutoff,fs_hz;bool sym;std::size_t warm,measured;fs::path out;};struct P{std::string n;int i;zkx::common::ResourceSample h,r,g;};struct E{std::vector<double>cpu,gpu,ct,gt;std::vector<P>cp,gp;std::string man,typed,id,cd,gd,preview0,preview1,outdt{"FP32"};};
C cli(int n,char**a){std::map<std::string,std::string>v;for(int i=1;i<n;i+=2){if(i+1>=n)throw std::invalid_argument("CLI");v.emplace(std::string(a[i]).substr(2),a[i+1]);}auto g=[&](const char*k,const char*d=nullptr){auto x=v.find(k);if(x!=v.end())return x->second;if(d)return std::string(d);throw std::invalid_argument(k);};return{g("dtype"),std::stoi(g("n")),std::stoi(g("taps","9")),std::stoi(g("batch","1")),std::stod(g("cutoff","60")),std::stod(g("fs","1000")),g("sym","true")=="true",std::stoull(g("warmup")),std::stoull(g("measured")),g("output")};}
zkx::common::ResourceSample gs(){return zkx::common::sample_gpu_used([]{auto i=cusignal::cuda_utils::current_memory_info();return static_cast<std::int64_t>(i.total_bytes-i.free_bytes);},"cudaMemGetInfo.total_minus_free");}P ph(const char*n,int i,bool g){return{n,i,zkx::common::sample_cpu_heap(),zkx::common::sample_cpu_rss(),g?gs():zkx::common::ResourceSample{false,0,"NA","CPU"}};}template<class T>T cv(double x){return static_cast<T>(x);}template<>__half cv<__half>(double x){return __float2half_rn(static_cast<float>(x));}template<class T>double ld(T x){return static_cast<double>(x);}template<>double ld<__half>(__half x){return __half2float(x);}template<class T>std::string dg(const std::vector<T>&v){return zkx::remaining_operator_case::sha256_hex(std::string(reinterpret_cast<const char*>(v.data()),v.size()*sizeof(T)));}template<class T>std::vector<double>flat(const std::vector<T>&v){std::vector<double>o;o.reserve(v.size());for(auto x:v)o.push_back(ld(x));return o;}std::vector<float>narrow(const std::vector<double>&v){std::vector<float>o(v.size());for(std::size_t i=0;i<v.size();++i)o[i]=static_cast<float>(v[i]);return o;}
template<class T>std::vector<T> signal(int n,int seed){std::vector<T>v(n);for(int i=0;i<n;++i){double x=3*std::sin(i*.071)+2*std::cos(i*.037)+((i*17+seed)%11-5)*.125;if constexpr(std::is_integral_v<T>)x=std::round(x);v[i]=cv<T>(x);}return v;}template<class T>std::vector<T> taps(int n){std::vector<T>v(n);for(int i=0;i<n;++i)v[i]=cv<T>(i==n/2?4:(i%2?1:0));return v;}template<class T>std::string prev(const std::vector<T>&v){std::vector<std::size_t>q;if(v.size()<=6)for(std::size_t i=0;i<v.size();++i)q.push_back(i);else q={0,1,2,3,v.size()-2,v.size()-1};std::ostringstream o;o<<std::setprecision(9);for(std::size_t j=0;j<q.size();++j){if(j)o<<';';o<<"i="<<q[j]<<':'<<ld(v[q[j]]);}return o.str();}template<class F>std::vector<double>meas(std::size_t w,std::size_t n,F f){for(std::size_t i=0;i<w;++i)f();std::vector<double>v;for(std::size_t i=0;i<n;++i){auto a=std::chrono::steady_clock::now();f();auto b=std::chrono::steady_clock::now();v.push_back(std::chrono::duration<double,std::milli>(b-a).count());}return v;}
template<class T>E run(const C&c){E e;std::string op=kOp;if(c.batch<=0)throw std::invalid_argument("batch");T marker=cv<T>(1),cut=cv<T>(c.cutoff);std::vector<T>x,b;std::vector<float>window;if(op=="firwin"){auto wd=cusignal::hamming_typed_cpu<float>(c.n,true);window=narrow(wd);e.preview0="i=0:"+std::to_string(ld(cut));e.preview1=prev(window);std::vector<T>z{cut};e.typed=dg(z);e.man="cutoff:"+c.dt+":sha256="+e.typed+"|window:FP32:sha256="+dg(window)+"|fs="+std::to_string(c.fs_hz)+"|batch="+std::to_string(c.batch);}else if(op=="firfilter"){x=signal<T>(c.n,29);b=taps<T>(c.taps);e.preview0=prev(b);e.preview1=prev(x);e.typed=dg(x);e.man="b:"+c.dt+":sha256="+dg(b)+"|x:"+c.dt+":sha256="+e.typed;}else{std::vector<T>z{marker};e.typed=dg(z);e.preview0="i=0:n="+std::to_string(c.n)+",sym="+(c.sym?"true":"false")+",dtype="+c.dt;e.man="request_dtype:"+c.dt+":sha256="+e.typed+"|n="+std::to_string(c.n)+"|sym="+(c.sym?"true":"false");}e.id=zkx::remaining_operator_case::sha256_hex(e.man);std::vector<float>cr,gr;
auto cpu=[&]{if(op=="hamming")cr=narrow(cusignal::hamming_typed_cpu<T>(c.n,c.sym));else if(op=="firwin"){cusignal::FirwinOptions o;o.window_mode=cusignal::FirwinWindowMode::explicit_values;o.window=std::vector<double>(window.begin(),window.end());o.pass_zero=cusignal::FirwinPassZero::boolean_true;o.scale=true;o.fs=c.fs_hz;cr.clear();cr.reserve(static_cast<std::size_t>(c.n)*c.batch);for(int batch=0;batch<c.batch;++batch){auto one=narrow(cusignal::firwin_typed_cpu<T>(c.n,std::vector<T>{cut},o));cr.insert(cr.end(),one.begin(),one.end());}}else{cusignal::FirfilterOptions o;o.shape={c.n};o.axis=-1;cr=cusignal::firfilter_typed_cpu(b,x,o).y;}};
auto gpu=[&]{if(op=="hamming"){cusignal::DeviceArray<float>o(c.n);cusignal::hamming_resident_device<T>(c.n,o,c.sym);gr=o.to_host();}else if(op=="firwin"){auto dc=cusignal::DeviceArray<T>::from_host(std::vector<T>{cut});auto dw=cusignal::DeviceArray<float>::from_host(window);cusignal::DeviceArray<float>o(c.n);gr.clear();gr.reserve(static_cast<std::size_t>(c.n)*c.batch);for(int batch=0;batch<c.batch;++batch){cusignal::firwin_lowpass_explicit_window_resident_device(c.n,dc,dw,o,static_cast<float>(c.fs_hz),true);auto one=o.to_host();gr.insert(gr.end(),one.begin(),one.end());}}else{auto db=cusignal::DeviceArray<T>::from_host(b),dx=cusignal::DeviceArray<T>::from_host(x);cusignal::FirfilterOptions o;o.shape={c.n};o.axis=-1;cusignal::FirfilterDeviceResult y;cusignal::firfilter_device(db,dx,y,o);gr=y.y.to_host();}cusignal::cuda_utils::synchronize_stream();};e.ct=meas(c.warm,c.measured,cpu);e.gt=meas(c.warm,c.measured,gpu);
e.cp.push_back(ph("before",0,0));e.cp.push_back(ph("allocate",1,0));e.cp.push_back(ph("h2d",2,0));cpu();e.cp.push_back(ph("execute_sync",3,0));e.cpu=flat(cr);e.cd=dg(cr);e.cp.push_back(ph("d2h",4,0));cr.clear();e.cp.push_back(ph("release_sync",5,0));e.cp.push_back(ph("after",6,0));
e.gp.push_back(ph("before",0,1));cusignal::DeviceArray<T>d0,d1;cusignal::DeviceArray<float>df,dw;cusignal::FirfilterDeviceResult fy;if(op=="hamming"||op=="firwin")df=cusignal::DeviceArray<float>(c.n);e.gp.push_back(ph("allocate",1,1));if(op=="firwin"){d0=cusignal::DeviceArray<T>::from_host(std::vector<T>{cut});dw=cusignal::DeviceArray<float>::from_host(window);}else if(op=="firfilter"){d0=cusignal::DeviceArray<T>::from_host(b);d1=cusignal::DeviceArray<T>::from_host(x);}e.gp.push_back(ph("h2d",2,1));if(op=="hamming")cusignal::hamming_resident_device<T>(c.n,df,c.sym);else if(op=="firwin")for(int batch=0;batch<c.batch;++batch)cusignal::firwin_lowpass_explicit_window_resident_device(c.n,d0,dw,df,static_cast<float>(c.fs_hz),true);else{cusignal::FirfilterOptions o;o.shape={c.n};o.axis=-1;cusignal::firfilter_device(d0,d1,fy,o);}cusignal::cuda_utils::synchronize_stream();e.gp.push_back(ph("execute_sync",3,1));if(op=="firfilter")gr=fy.y.to_host();else if(op=="firwin"){auto one=df.to_host();gr.clear();gr.reserve(static_cast<std::size_t>(c.n)*c.batch);for(int batch=0;batch<c.batch;++batch)gr.insert(gr.end(),one.begin(),one.end());}else gr=df.to_host();e.gpu=flat(gr);e.gd=dg(gr);e.gp.push_back(ph("d2h",4,1));d0={};d1={};df={};dw={};fy={};gr.clear();cusignal::cuda_utils::synchronize_stream();e.gp.push_back(ph("release_sync",5,1));e.gp.push_back(ph("after",6,1));return e;}
void sa(std::ostream&o,const std::vector<double>&v){o<<'[';for(std::size_t i=0;i<v.size();++i){if(i)o<<',';o<<std::setprecision(17)<<v[i];}o<<']';}void sr(std::ostream&o,const zkx::common::ResourceSample&s){o<<"{\"available\":"<<(s.available?"true":"false")<<",\"bytes\":"<<(s.available?std::to_string(s.bytes):"null")<<'}';}void st(std::ostream&o,const std::vector<P>&v){o<<'[';for(std::size_t i=0;i<v.size();++i){if(i)o<<',';o<<"{\"phase\":\""<<v[i].n<<"\",\"phase_index\":"<<v[i].i<<",\"heap\":";sr(o,v[i].h);o<<",\"rss\":";sr(o,v[i].r);o<<",\"gpu\":";sr(o,v[i].g);o<<'}';}o<<']';}int dp(const C&c,E&e){if(c.dt=="FP32")e=run<float>(c);else if(c.dt=="FP16")e=run<__half>(c);else if(c.dt=="INT32")e=run<std::int32_t>(c);else if(c.dt=="INT16")e=run<std::int16_t>(c);else if(c.dt=="INT8")e=run<std::int8_t>(c);else return 2;return 0;}}
int main(int n,char**a){try{C c=cli(n,a);E e;if(dp(c,e))return 2;auto m=zkx::common::compare(e.cpu,e.gpu,1e-12);if(fs::exists(c.out))throw std::runtime_error("exists");std::ofstream o(c.out);o<<"{\"operator\":\""<<kOp<<"\",\"requested_dtype\":\""<<c.dt<<"\",\"output_dtype\":\""<<e.outdt<<"\",\"backend\":\"not_applicable\",\"n\":"<<c.n<<",\"taps\":"<<c.taps<<",\"batch_count\":"<<c.batch<<",\"output_count\":"<<e.cpu.size()<<",\"typed_input_manifest\":\""<<e.man<<"\",\"typed_array_digest\":\""<<e.typed<<"\",\"actual_input_digest\":\""<<e.id<<"\",\"preview0\":\""<<e.preview0<<"\",\"preview1\":\""<<e.preview1<<"\",\"cpu_output_digest\":\""<<e.cd<<"\",\"gpu_output_digest\":\""<<e.gd<<"\",\"mse\":"<<m.mse<<",\"rmse\":"<<m.rmse<<",\"relative_l2\":"<<m.relative_l2<<",\"relative_linf\":"<<m.relative_linf<<",\"cpu_samples_ms\":";sa(o,e.ct);o<<",\"gpu_samples_ms\":";sa(o,e.gt);o<<",\"cpu_trace\":";st(o,e.cp);o<<",\"gpu_trace\":";st(o,e.gp);o<<"}\n";std::cout<<"OPERATOR_CASE_FILTER_PROBE PASS operator="<<kOp<<" dtype="<<c.dt<<'\n';return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}}
